/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2024-01-22 05:30:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.meet;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import member.vo.MemberVO;
import meet.vo.MeetVO;
import meet.vo.MbVO;
import member.vo.MemberVO;

public final class meetdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/meet/../include/footer.jsp", Long.valueOf(1705885420768L));
    _jspx_dependants.put("/meet/../include/loginheader.jsp", Long.valueOf(1705900390950L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.vo.MemberVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("meet.vo.MeetVO");
    _jspx_imports_classes.add("meet.vo.MbVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MeetVO mv = (MeetVO) request.getAttribute("mv");
	List<MbVO> hugiList = (List<MbVO>) request.getAttribute("hugiList");
	int comment = hugiList.size();
@SuppressWarnings("unchecked")
//List<MbVO> hugiList = (List<MbVO>) request.getAttribute("hugiList");
//MemberVO mem = (MemberVO) request.getAttribute("LOGIN_USER"); 이거말고
MemberVO mem = (MemberVO) session.getAttribute("LOGIN_USER"); //이거

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO mmv = (MemberVO) session.getAttribute("LOGIN_USER");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\">\t\t\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>nawa!</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Meta Tags -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<meta name=\"author\" content=\"Webestica.com\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Eduport- LMS, Education and Course Theme\">\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Favicon -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/nawa/assets/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Google Font -->\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Plugins CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/font-awesome/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/bootstrap-icons/bootstrap-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/choices/css/choices.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Theme CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header START -->\r\n");
      out.write("<header class=\"navbar-light navbar-sticky\">\r\n");
      out.write("\t<!-- Logo Nav START -->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-xl\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Logo START -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">\r\n");
      out.write("\t\t\t\t<img class=\"light-mode-item navbar-brand-item\" src=\"/nawa/assets/images/5조_제목_로고-removebg-preview.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t<img class=\"dark-mode-item navbar-brand-item\" src=\"/nawa/assets/images/logo-light.svg\" alt=\"logo\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<!-- Logo END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Responsive navbar toggler -->\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler ms-auto\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\" aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-animation\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main navbar START -->\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse w-100 collapse\" id=\"navbarCollapse\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Nav Main menu START -->\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav navbar-nav-scroll mx-auto\">\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 1 Demos -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"demoMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"demoMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/list.do\">전체게시판</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-3.html\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-6.html\">질문게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-5.html\">익명게시판</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-4.html\">홍보</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 2 Pages -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"pagesMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">소모임</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"pagesMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/meetList\">모임 검색하기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">About</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Hero Banner</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-list.html\">Instructor List</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-single.html\">Instructor Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"become-instructor.html\">Become an Instructor</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"abroad-single.html\">Abroad Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"workshop-detail.html\">Workshop Detail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"event-detail.html\">Event Detail</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 3 Account -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"accounntMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">레슨</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"accounntMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-tie fa-fw me-1\"></i>강 사</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-dashboard.html\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>Dashboard</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-manage-course.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>Courses</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-create-course.html\"><i class=\"bi bi-file-earmark-plus-fill fa-fw me-1\"></i>Create Course</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-added.html\"><i class=\"bi bi-file-check-fill fa-fw me-1\"></i>Course Added</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>Quiz</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-earning.html\"><i class=\"fas fa-chart-line fa-fw me-1\"></i>Earnings</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-studentlist.html\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>Students</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-order.html\"><i class=\"bi bi-cart-check-fill fa-fw me-1\"></i>Orders</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-review.html\"><i class=\"bi bi-star-fill fa-fw me-1\"></i>Reviews</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-payout.html\"><i class=\"fas fa-wallet fa-fw me-1\"></i>Payout</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>학 생</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/list.do\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>강의전체보기</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><i class=\"bi bi-card-checklist fa-fw me-1\"></i>운동강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-list.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>음악강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-resume.html\"><i class=\"far fa-fw fa-file-alt me-1\"></i>어학강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>개발강의 </a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-payment-info.html\"><i class=\"bi bi-credit-card-2-front-fill fa-fw me-1\"></i>게임강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>공예강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>기타강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"admin-dashboard.html\"><i class=\"fas fa-user-cog fa-fw me-1\"></i>Admin</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\tNav item 5 link\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"#\" id=\"advanceMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-ellipsis-h\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end min-w-auto\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://support.webestica.com/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-warning fa-fw bi bi-life-preserver me-2\"></i>Support\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"docs/index.html\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-danger fa-fw bi bi-card-text me-2\"></i>Documentation\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://eduport.webestica.com/rtl/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-info fa-fw bi bi-toggle-off me-2\"></i>RTL demo\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://themes.getbootstrap.com/store/webestica/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-success fa-fw bi bi-cloud-download-fill me-2\"></i>Buy Eduport!\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"docs/alerts.html\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-orange fa-fw bi bi-puzzle-fill me-2\"></i>Components\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("                <a class=\"dropdown-item\" href=\"docs/snippets.html\">\r\n");
      out.write("                  <i class=\"text-purple fa-fw bi bi-stickies-fill me-2\"></i>Snippets\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>      \r\n");
      out.write("\t\t\t\t<!-- Nav Main menu END -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Nav Search START -->\r\n");
      out.write("\t\t\t\t<!-- <div class=\"nav my-3 my-xl-0 px-4 flex-nowrap align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"nav-item w-100\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"position-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control pe-5 bg-transparent\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"bg-transparent p-2 position-absolute top-50 end-0 translate-middle-y border-0 text-primary-hover text-reset\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-search fs-6 \"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- Nav Search END -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Main navbar END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ############################################ 회원일 경우 달라질헤더 부분  ############################## -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown ms-1 ms-lg-0\">\r\n");
      out.write("\t\t\t\t<a class=\"avatar avatar-sm p-0\" href=\"#\" id=\"profileDropdown\" role=\"button\" data-bs-auto-close=\"outside\" data-bs-display=\"static\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<img class=\"avatar-img rounded-circle\" src=\"/nawa/assets/images/avatar/img.png\" alt=\"avatar\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu dropdown-animation dropdown-menu-end shadow pt-3\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("\t\t\t\t\t<!-- Profile info -->\r\n");
      out.write("\t\t\t\t\t<li class=\"px-3 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Avatar -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"avatar me-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"avatar-img rounded-circle shadow\" src=\"/nawa/image/profile/");
      out.print(mmv.getStreFileNm() );
      out.write("\" alt=\"avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"h6\" href=\"#\">");
      out.print(mmv.getMem_nick() );
      out.write("</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"small m-0\">");
      out.print(mmv.getMem_email() );
      out.write("</p> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t<!-- Links -->\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.jsp\"><i class=\"bi bi-person fa-fw me-2\"></i>마이 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit_profile.jsp\"><i class=\"bi bi-gear fa-fw me-2\"></i>정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item bg-danger-soft-hover\" href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.do\"><i class=\"bi bi-power fa-fw me-2\"></i>로그 아웃</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><i class=\"bi bi-info-circle fa-fw me-2\"></i>Help</a></li>\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Profile END -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- Logo Nav END -->\r\n");
      out.write("</header>\r\n");
      out.write("<!-- Header END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- **************** MAIN CONTENT START **************** -->\r\n");
      out.write("<main>\r\n");
      out.write("\t<!-- =======================\r\n");
      out.write("Main banner START -->\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"pt-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Card item START -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card overflow-hidden h-400px h-xl-600px rounded-3\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"background-image: url(assets/images/bg/08.jpg); background-position: center left; background-size: cover;\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Background dark overlay -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bg-overlay bg-dark opacity-6\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Card image overlay -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-img-overlay d-flex align-items-start flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Card overlay Top -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w-100 mb-auto d-flex justify-content-end\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-sm btn-white mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"bi bi-share\"></i> Share\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Card overlay bottom -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w-100 mt-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row p-0 p-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-11 col-lg-7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h1 class=\"text-white\">");
      out.print(mv.getMeet_name());
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"text-white\">");
      out.print(mv.getMem_nick());
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Card item END -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- =======================\r\n");
      out.write("Main banner END -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- =======================\r\n");
      out.write("Page content START -->\r\n");
      out.write("\t<section class=\"pt-0\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row g-4 g-lg-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main content START -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 order-2\">\r\n");
      out.write("\t\t\t\t\t<!-- Organization and time -->\r\n");
      out.write("\t\t\t\t\t<div class=\"bg-light rounded-3 p-3 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row g-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Organization -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"small \">모임장ID</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Avatar -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"avatar align-middle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\" avatar-img rounded-1 bg-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"  text-white position-absolute top-50 start-50 translate-middle fw-bold bi bi-person-circle\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Info -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ms-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-0\">");
      out.print(mv.getMem_id());
      out.write("</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- <small>2.4k followers</small> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Location -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"small\">Location:</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Avatar -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"avatar align-middle flex-shrink-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"avatar-img rounded-2 bg-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"position-absolute top-50 start-50 translate-middle text-white\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi bi-geo-alt-fill\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"fw-normal mb-0 ms-2\">");
      out.print(mv.getMeet_loc());
      out.write("</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Date & Time -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"small\">모임시간:</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Avatar -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"avatar align-middle flex-shrink-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"avatar-img rounded-2 bg-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"position-absolute top-50 start-50 translate-middle text-white\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi bi-calendar-fill\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ms-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"fw-normal mb-0\">");
      out.print(mv.getMeet_day());
      out.write("</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small>");
      out.print(mv.getMeet_time());
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t\t\t<h5>< 소모임 상세설명 ></h5>\r\n");
      out.write("\t\t\t\t\t<style>\r\n");
      out.write("  \t\t\t\t\t.meet-content {\r\n");
      out.write("   \t\t\t\t\tborder: 3px solid #001; /* 테두리 스타일 및 색상을 지정합니다. */\r\n");
      out.write("   \t\t\t\t\tpadding: 20px; /* 내부 여백을 추가하여 텍스트와 테두리 사이의 공백을 늘립니다. */\r\n");
      out.write("    \t\t\t\twidth: 800px; /* 원하는 너비를 지정합니다. */\r\n");
      out.write("    \t\t\t\tborder-radius: 10px; /* 모서리를 동그랗게 만듭니다. */\r\n");
      out.write("    \t\t\t\tbox-shadow: 5px 5px 15px rgba(0, 0, 0, 0.1); /* 그림자를 추가하여 입체감을 부여합니다. */\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</style>\r\n");
      out.write("\t\t\t\t\t<div class=\"meet-content\">\r\n");
      out.write("  \t\t\t\t\t\t");
      out.print( mv.getMeet_info() );
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- <p>We focus a great deal on the</p> -->\r\n");
      out.write("\t\t\t\t\t<!-- Counter -->\r\n");
      out.write("\t\t\t\t\t<div class=\"card card-body bg-light p-4 mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row g-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Visitors -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"bi bi-globe fs-4\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">level</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5 class=\"mb-0\">");
      out.print(mv.getMeet_level());
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Registered -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"bi bi-person-plus fs-4\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">후기</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5 class=\"mb-0\">");
      out.print(comment );
      out.write(" 개</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Attendance -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"bi bi-people fs-4\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0\">참여인원</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5 class=\"mb-0\">");
      out.print(mv.getMeet_cnt());
      out.write('명');
      out.write('/');
      out.print(mv.getMeet_limit());
      out.write("명\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Main content END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Left sidebar START -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 order-1 order-lg-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card card-body shadow\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 쿼리스트링으로 모임번호보내기 ? 로  -->\r\n");
      out.write("\t\t\t\t\t\t<!-- <a class=\"btn btn-primary w-100\" href=\"#\"> 모임 신청하기 페이지로(만들어야함) </a> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 버튼만들기------------------ -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <a class=\"page-link\" href=\"#\" onclick=\"goToInsertMeet()\">글 작성</a> -->\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mbList?meetNo=");
      out.print(mv.getMeet_no());
      out.write("'\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-primary w-100\">게시판이동하기</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"page-item mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <a class=\"page-link\" href=\"#\" onclick=\"goToInsertMeet()\">글 작성</a> -->\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/meetJoin?meetNo=");
      out.print(mv.getMeet_no());
      out.write("'\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-primary w-100 bi bi-send-fill\">신청하기</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- <!-- 모달창 클릭 만들기----------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\tButton to Open the Modal\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"modal\" data-bs-target=\"#myModal\">모임 신청하기\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tThe Modal\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tModal Header\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">Modal Heading</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-close\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tModal body\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">Modal body..</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tModal footer\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-unstyled mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <li class=\"d-flex justify-content-between mb-3\"> <span class=\"w-150px\">Ticket Price:</span> <h6 class=\"text-end mb-0\"> $210.00 </h6></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"d-flex justify-content-between mb-3\"> <span class=\"w-150px\">Entry fees:</span> <h6 class=\"text-end mb-0\"> $1 per ticket </h6></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"d-flex justify-content-between mb-3\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"w-150px\">Address:</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"text-end mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(mv.getMeet_loc());
      out.print(mv.getMeet_loc_detail());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h6></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 지도부분 -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <iframe class=\"w-100 d-block rounded-bottom\" height=\"230\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.9663095343008!2d-74.00425878428698!3d40.74076684379132!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c259bf5c1654f3%3A0xc80f9cfce5383d5d!2sGoogle!5e0!3m2!1sen!2sin!4v1586000412513!5m2!1sen!2sin\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border: 0;\" aria-hidden=\"false\" tabindex=\"0\"></iframe> -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"map\" style=\"width: 100%; height: 350px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"editButton_\" class=\"btn btn-primary w-100\" onclick = \"location.href='");
      out.print(request.getContextPath() );
      out.write("/meetUpdate?meetNo=");
      out.print(mv.getMeet_no());
      out.write("'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t수정\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"deleteButton_\" class=\"btn btn-primary w-100\" onclick =\"location.href='");
      out.print(request.getContextPath());
      out.write("/meetDelete?meetNo=");
      out.print(mv.getMeet_no());
      out.write("'\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t삭제\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Left sidebar END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 오른쪽 사이드바 끝 -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- ******************************************** -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<h1></h1>\r\n");
      out.write("\t\t\t<h1></h1>\r\n");
      out.write("\t\t\t<h1></h1>\r\n");
      out.write("\t\t\t<h1></h1>\r\n");
      out.write("\t\t\t<h1></h1>\r\n");
      out.write("\t\t\t<h1></h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--*******************************  -->\r\n");
      out.write("\t\t<!-- 후기 div만들기전 공간마 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Student review START -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-md-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card bg-transparent border\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Card header START -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header border-bottom bg-light\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"mb-0\">All Reviews</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Card header END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Card body START -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body pb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Table START -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-responsive border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"table table-dark-gray align-middle p-4 mb-0 table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Table head -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"table table-dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <th scope=\"col\" class=\"border-0 rounded-start\" >ID</th> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"border-0 rounded-start\">닉네임 |\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t후기제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"border-0\">|후기내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <th scope=\"col\" class=\"border-0\">|Rating</th> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"border-0 rounded-end\">|Action</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Table body START -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (MbVO hg : hugiList) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Table Data -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"d-flex align-items-center position-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- Image -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"h6 fw-light mb-0\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi bi-person-check-fill\"></i> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"stretched-link\">");
      out.print(hg.getMem_nick());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"mb-0 ms-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"stretched-link\">");
      out.print(hg.getMb_title());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Table Data -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"table-responsive-title mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">");
      out.print(hg.getMb_cont());
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 별점 매기기 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- Table Data -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"#\" class=\"btn btn-sm btn-info-soft mb-0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-bs-toggle=\"modal\" data-bs-target=\"#viewReview\">View</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Table body END -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Table END -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Card body END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Card footer START -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-footer bg-transparent\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Pagination START -->\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"d-sm-flex justify-content-sm-between align-items-sm-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Pagination -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <nav class=\"d-flex justify-content-center mb-0\" aria-label=\"navigation\">\r\n");
      out.write("                    <ul class=\"pagination pagination-sm pagination-primary-soft d-inline-block d-md-flex rounded mb-0\">\r\n");
      out.write("                        <li class=\"page-item mb-0\"><a class=\"page-link\" href=\"#\" tabindex=\"-1\"><i class=\"fas fa-angle-left\"></i></a></li>\r\n");
      out.write("                        <li class=\"page-item mb-0\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                        <li class=\"page-item mb-0 active\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                        <li class=\"page-item mb-0\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                        <li class=\"page-item mb-0\"><a class=\"page-link\" href=\"#\"><i class=\"fas fa-angle-right\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 페이징 처리된 페이지 목록 시작 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"pagination\" class=\"container mt-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										Integer currentPageObj = (Integer) request.getAttribute("currentPage");
									Integer totalPagesObj = (Integer) request.getAttribute("totalPages");

									int currentPage = (currentPageObj != null) ? currentPageObj : 1;
									int totalPages = (totalPagesObj != null) ? totalPagesObj : 1;

									int maxPagesToShow = 5; // 보여줄 최대 페이지 수

									int startPage = Math.max(1, currentPage - maxPagesToShow / 2);
									int endPage = Math.min(startPage + maxPagesToShow - 1, totalPages);
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- '이전' 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"container text-center col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"pagination justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!--     \t<ul class=\"pagination pagination-primary-soft rounded justify-content-center\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!--     \t<ul class=\"pagination pagination-outline rounded justify-content-center\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												if (currentPage > 1) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"./list.do?page=");
      out.print(currentPage - 1);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\"><i class=\"fas fa-angle-double-left\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												} else {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 페이지 목록 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												if (startPage > 1) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a href=\"./list.do?page=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											if (startPage > 2) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><span class=\"page-item disabled\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"ellipsis\"><a class=\"page-link\" href=\"#\">...</a></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}

											for (int i = startPage; i <= endPage; i++) {
											if (i == currentPage) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item active\"><a class=\"page-link\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\"> <span class=\"current-page\"> ");
      out.print(i);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												} else {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a href=\"./list.do?page=");
      out.print(i);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\">");
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											}

											if (endPage < totalPages - 1) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><span class=\"page-item disabled\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"ellipsis\"><a class=\"page-link\" href=\"#\">...</a></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											if (endPage < totalPages) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thref=\"./list.do?page=");
      out.print(totalPages);
      out.write("\" class=\"page-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(totalPages);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 페이지 목록 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- '다음' 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												if (currentPage < totalPages) {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"./list.do?page=");
      out.print(currentPage + 1);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"page-link\"><i class=\"fas fa-angle-double-right\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												} else {
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- '다음' 버튼 끝 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 글쓰기 버튼\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <button type=\"submit\" class=\"btn btn-dark\" id=\"writeButton\" style=\"height:34px\" onclick=\"location.href='./insert.do'\">write</button> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 페이징 처리된 페이지 목록 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Pagination END -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Card footer END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Student review END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- 페이지 콘텐츠 끝 -->\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"pt-5 bg-light\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- Row START -->\r\n");
      out.write("\t\t<div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 1 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<!-- logo -->\r\n");
      out.write("\t\t\t\t<a class=\"me-0\" href=\"/nawa/index.jsp\">\r\n");
      out.write("\t\t\t\t\t<img class=\"light-mode-item h-40px\" src=\"/nawa/assets/images/title_logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"list-inline mb-0 mt-3\">\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-facebook\" href=\"#\"><i class=\"fab fa-fw fa-facebook-f\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-instagram\" href=\"#\"><i class=\"fab fa-fw fa-instagram\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-twitter\" href=\"#\"><i class=\"fab fa-fw fa-twitter\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-linkedin\" href=\"#\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a> </li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Widget 1 END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 2 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t<div class=\"row g-4\">\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Company</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">News and Blogs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Library</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Career</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Community</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Documentation</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Faq</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Forum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Sitemap</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Teaching</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Become a teacher</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">How to guide</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Widget 2 END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 3 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Contact</h5>\r\n");
      out.write("\t\t\t\t<!-- Time -->\r\n");
      out.write("\t\t\t\t<p class=\"mb-2\">\r\n");
      out.write("\t\t\t\t\tToll free:<span class=\"h6 fw-light ms-2\">+1234 568 963</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"d-block small\">(9:AM to 8:PM IST)</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"mb-0\">Email:<span class=\"h6 fw-light ms-2\">example@gmail.com</span></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row g-2 mt-2\">\r\n");
      out.write("\t\t\t\t\t<!-- Google play store button -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3 col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/nawa/assets/images/client/google-play.svg\" alt=\"\"> </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- App store button -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3 col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/nawa/assets/images/client/app-store.svg\" alt=\"app-store\"> </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> <!-- Row END -->\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<!-- Widget 3 END -->\r\n");
      out.write("\t\t</div><!-- Row END -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Divider -->\r\n");
      out.write("\t\t<hr class=\"mt-4 mb-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bottom footer -->\r\n");
      out.write("\t\t<div class=\"py-3\">\r\n");
      out.write("\t\t\t<div class=\"container px-0\">\r\n");
      out.write("\t\t\t\t<div class=\"d-lg-flex justify-content-between align-items-center py-3 text-center text-md-left\">\r\n");
      out.write("\t\t\t\t\t<!-- copyright text -->\r\n");
      out.write("\t\t\t\t\t<div class=\"text-body text-primary-hover\"> Copyrights ÃÂ©2023 Eduport. Build by <a href=\"https://www.webestica.com/\" target=\"_blank\" class=\"text-body\">Webestica</a></div>\r\n");
      out.write("\t\t\t\t\t<!-- copyright links-->\r\n");
      out.write("\t\t\t\t\t<div class=\"justify-content-center mt-3 mt-lg-0\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav list-inline justify-content-center mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Language selector -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropup mt-0 text-center text-sm-end\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"dropdown-toggle nav-link\" href=\"#\" role=\"button\" id=\"languageSwitcher\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-globe me-2\"></i>Language\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu min-w-auto\" aria-labelledby=\"languageSwitcher\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/uk.svg\" alt=\"\">English</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/gr.svg\" alt=\"\">German </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/sp.svg\" alt=\"\">French</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a class=\"nav-link\" href=\"#\">Terms of use</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a class=\"nav-link pe-0\" href=\"#\">Privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- =======================\r\n");
      out.write("Footer END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Back to top -->\r\n");
      out.write("<div class=\"back-top\">\r\n");
      out.write("\t<i\r\n");
      out.write("\t\tclass=\"bi bi-arrow-up-short position-absolute top-50 start-50 translate-middle\"></i>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"/nawa/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Template Functions -->\r\n");
      out.write("<script src=\"/nawa/assets/js/functions.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=79549d33b8659b656efac22c4abff096&libraries=services\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var addressData = {\r\n");
      out.write("        meetLoc: '");
      out.print(mv.getMeet_loc());
      out.write("',\r\n");
      out.write("        meetLocDetail: '");
      out.print(mv.getMeet_loc_detail());
      out.write("'\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("\tmapOption = {\r\n");
      out.write("\t\tcenter : new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표\r\n");
      out.write("\t\tlevel : 3\r\n");
      out.write("\t// 지도의 확대 레벨\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t//지도를 생성합니다    \r\n");
      out.write("\tvar map = new kakao.maps.Map(mapContainer, mapOption);\r\n");
      out.write("\r\n");
      out.write("\t//주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("\tvar geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("\r\n");
      out.write("\t//주소로 좌표를 검색합니다\r\n");
      out.write("\tgeocoder\r\n");
      out.write("\t\t\t.addressSearch(\r\n");
      out.write("\t\t\t\t\taddressData.meetLoc + ' ' + addressData.meetLocDetail,\r\n");
      out.write("\t\t\t\t\tfunction(result, status) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 정상적으로 검색이 완료됐으면 \r\n");
      out.write("\t\t\t\t\t\tif (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar coords = new kakao.maps.LatLng(result[0].y,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tresult[0].x);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 결과값으로 받은 위치를 마커로 표시합니다\r\n");
      out.write("\t\t\t\t\t\t\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\t\t\tposition : coords\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 인포윈도우로 장소에 대한 설명을 표시합니다\r\n");
      out.write("\t\t\t\t\t\t\tvar infowindow = new kakao.maps.InfoWindow(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcontent : '<div style=\"width:150px;text-align:center;padding:6px 0;\">모일 장소!</div>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tinfowindow.open(map, marker);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 지도의 중심을 결과값으로 받은 위치로 이동시킵니다\r\n");
      out.write("\t\t\t\t\t\t\tmap.setCenter(coords);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // 예제로 로그인한 회원 아이디와 해당 페이지의 모임을 만든 회원 아이디를 설정\r\n");
      out.write("    var loggedInUserId = \"");
      out.print(mem.getMem_id());
      out.write("\";\r\n");
      out.write("    var meetupCreatorId = \"");
      out.print(mv.getMem_id());
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\t// 버튼 요소 가져오기\r\n");
      out.write("\tvar editButton = document.getElementById(\"editButton_\");\r\n");
      out.write("\tvar deleteButton = document.getElementById(\"deleteButton_\");\r\n");
      out.write("\tconsole.log(editButton);\r\n");
      out.write("\r\n");
      out.write("\t// 로그인한 회원 아이디와 모임을 만든 회원 아이디 비교\r\n");
      out.write("\tif (loggedInUserId === meetupCreatorId) {\r\n");
      out.write("\t\t// 권한이 있는 경우: 수정, 삭제 버튼 활성화\r\n");
      out.write("\t\teditButton.style.display = \"block\"; // 수정 버튼을 보이도록 설정\r\n");
      out.write("\t\tdeleteButton.style.display = \"block\"; // 삭제 버튼을 보이도록 설정\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\t// 권한이 없는 경우: 수정, 삭제 버튼 비활성화 및 모달창 표시\r\n");
      out.write("\t\teditButton.style.display = \"none\"; // 수정 버튼을 감추도록 설정\r\n");
      out.write("\t\tdeleteButton.style.display = \"none\"; // 삭제 버튼을 감추도록 설정\r\n");
      out.write("\r\n");
      out.write("\t\t// 모달창 띄우기 등 추가 작업을 수행할 수 있습니다.\r\n");
      out.write("\t\t//alert(\"권한이 없습니다!\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
