/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2024-01-22 05:51:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.vo.MemberVO;
import java.net.URLEncoder;
import java.util.List;
import board.vo.PostVO;
import member.vo.MemberVO;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/loginheader.jsp", Long.valueOf(1705900390950L));
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1705885420768L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.vo.MemberVO");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("board.vo.PostVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	
	if (session.getAttribute("LOGIN_USER") == null) {

      out.write("\r\n");
      out.write("      \t<script> alert(\"로그인이 필요합니다\");\r\n");
      out.write("      \tlocation.href = \"/nawa/index.jsp\"; </script> \r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write(" \t\r\n");

	MemberVO mv = (MemberVO) session.getAttribute("LOGIN_USER");

      out.write("\r\n");
      out.write("\r\n");

	List<PostVO> postList = (List<PostVO>)request.getAttribute("postList");
// 	BoardAtchFileVO bv = request.getAttribute("bv");
	
	String msg = session.getAttribute("msg") == null ? "" 
	: (String) session.getAttribute("msg");
	session.removeAttribute("msg");

	List<PostVO> searchList = (List<PostVO>)request.getAttribute("searchList");
	List<PostVO> catePostsList = (List<PostVO>)request.getAttribute("catePostsList");
	List<PostVO> bNotiList = (List<PostVO>)request.getAttribute("bNotiList");
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO mmv = (MemberVO) session.getAttribute("LOGIN_USER");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\">\t\t\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>nawa!</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Meta Tags -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<meta name=\"author\" content=\"Webestica.com\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Eduport- LMS, Education and Course Theme\">\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Favicon -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/nawa/assets/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Google Font -->\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Plugins CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/font-awesome/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/bootstrap-icons/bootstrap-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/choices/css/choices.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Theme CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header START -->\r\n");
      out.write("<header class=\"navbar-light navbar-sticky\">\r\n");
      out.write("\t<!-- Logo Nav START -->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-xl\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Logo START -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">\r\n");
      out.write("\t\t\t\t<img class=\"light-mode-item navbar-brand-item\" src=\"/nawa/assets/images/5조_제목_로고-removebg-preview.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t<img class=\"dark-mode-item navbar-brand-item\" src=\"/nawa/assets/images/logo-light.svg\" alt=\"logo\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<!-- Logo END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Responsive navbar toggler -->\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler ms-auto\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\" aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-animation\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main navbar START -->\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse w-100 collapse\" id=\"navbarCollapse\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Nav Main menu START -->\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav navbar-nav-scroll mx-auto\">\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 1 Demos -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"demoMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"demoMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/list.do\">전체게시판</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-3.html\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-6.html\">질문게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-5.html\">익명게시판</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-4.html\">홍보</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 2 Pages -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"pagesMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">소모임</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"pagesMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/meetList\">모임 검색하기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">About</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Hero Banner</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-list.html\">Instructor List</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-single.html\">Instructor Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"become-instructor.html\">Become an Instructor</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"abroad-single.html\">Abroad Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"workshop-detail.html\">Workshop Detail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"event-detail.html\">Event Detail</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 3 Account -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"accounntMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">레슨</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"accounntMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-tie fa-fw me-1\"></i>강 사</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-dashboard.html\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>Dashboard</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-manage-course.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>Courses</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-create-course.html\"><i class=\"bi bi-file-earmark-plus-fill fa-fw me-1\"></i>Create Course</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-added.html\"><i class=\"bi bi-file-check-fill fa-fw me-1\"></i>Course Added</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>Quiz</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-earning.html\"><i class=\"fas fa-chart-line fa-fw me-1\"></i>Earnings</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-studentlist.html\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>Students</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-order.html\"><i class=\"bi bi-cart-check-fill fa-fw me-1\"></i>Orders</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-review.html\"><i class=\"bi bi-star-fill fa-fw me-1\"></i>Reviews</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-payout.html\"><i class=\"fas fa-wallet fa-fw me-1\"></i>Payout</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>학 생</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/list.do\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>강의전체보기</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><i class=\"bi bi-card-checklist fa-fw me-1\"></i>운동강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-list.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>음악강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-resume.html\"><i class=\"far fa-fw fa-file-alt me-1\"></i>어학강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>개발강의 </a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-payment-info.html\"><i class=\"bi bi-credit-card-2-front-fill fa-fw me-1\"></i>게임강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>공예강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>기타강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"admin-dashboard.html\"><i class=\"fas fa-user-cog fa-fw me-1\"></i>Admin</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\tNav item 5 link\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"#\" id=\"advanceMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-ellipsis-h\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end min-w-auto\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://support.webestica.com/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-warning fa-fw bi bi-life-preserver me-2\"></i>Support\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"docs/index.html\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-danger fa-fw bi bi-card-text me-2\"></i>Documentation\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://eduport.webestica.com/rtl/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-info fa-fw bi bi-toggle-off me-2\"></i>RTL demo\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://themes.getbootstrap.com/store/webestica/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-success fa-fw bi bi-cloud-download-fill me-2\"></i>Buy Eduport!\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"docs/alerts.html\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-orange fa-fw bi bi-puzzle-fill me-2\"></i>Components\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("                <a class=\"dropdown-item\" href=\"docs/snippets.html\">\r\n");
      out.write("                  <i class=\"text-purple fa-fw bi bi-stickies-fill me-2\"></i>Snippets\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>      \r\n");
      out.write("\t\t\t\t<!-- Nav Main menu END -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Nav Search START -->\r\n");
      out.write("\t\t\t\t<!-- <div class=\"nav my-3 my-xl-0 px-4 flex-nowrap align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"nav-item w-100\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"position-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control pe-5 bg-transparent\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"bg-transparent p-2 position-absolute top-50 end-0 translate-middle-y border-0 text-primary-hover text-reset\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-search fs-6 \"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- Nav Search END -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Main navbar END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ############################################ 회원일 경우 달라질헤더 부분  ############################## -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown ms-1 ms-lg-0\">\r\n");
      out.write("\t\t\t\t<a class=\"avatar avatar-sm p-0\" href=\"#\" id=\"profileDropdown\" role=\"button\" data-bs-auto-close=\"outside\" data-bs-display=\"static\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<img class=\"avatar-img rounded-circle\" src=\"/nawa/assets/images/avatar/img.png\" alt=\"avatar\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu dropdown-animation dropdown-menu-end shadow pt-3\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("\t\t\t\t\t<!-- Profile info -->\r\n");
      out.write("\t\t\t\t\t<li class=\"px-3 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Avatar -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"avatar me-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"avatar-img rounded-circle shadow\" src=\"/nawa/image/profile/");
      out.print(mmv.getStreFileNm() );
      out.write("\" alt=\"avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"h6\" href=\"#\">");
      out.print(mmv.getMem_nick() );
      out.write("</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"small m-0\">");
      out.print(mmv.getMem_email() );
      out.write("</p> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t<!-- Links -->\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.jsp\"><i class=\"bi bi-person fa-fw me-2\"></i>마이 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit_profile.jsp\"><i class=\"bi bi-gear fa-fw me-2\"></i>정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item bg-danger-soft-hover\" href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.do\"><i class=\"bi bi-power fa-fw me-2\"></i>로그 아웃</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><i class=\"bi bi-info-circle fa-fw me-2\"></i>Help</a></li>\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Profile END -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- Logo Nav END -->\r\n");
      out.write("</header>\r\n");
      out.write("<!-- Header END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic+Coding&family=Noto+Sans+Mono:wght@200&family=Roboto+Flex:opsz,wght@8..144,200&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<!-- <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#listJsp {\r\n");
      out.write("padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("th {\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#postCate {\r\n");
      out.write("color: black;\r\n");
      out.write("}\r\n");
      out.write("#searchContainer, #searchForm {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  margin: 0px;\r\n");
      out.write("  padding: 0px;\r\n");
      out.write("}\r\n");
      out.write("#searchOptions, #searchBox, #searchButton{\r\n");
      out.write("padding: 4px;\r\n");
      out.write("}\r\n");
      out.write("#postNo, #postCate, #postWriter, #postDate, #listViewCnt, #postAtch {\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url(assets/images/pattern/05.png)\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("/*  float:right; */\r\n");
      out.write("/*  margin-left: auto; */\r\n");
      out.write(" align: right;\r\n");
      out.write("}\r\n");
      out.write("#notice{\r\n");
      out.write("background-color:rgb(239, 247, 254);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("<!-- =======================\r\n");
      out.write("Page Banner START -->\r\n");
      out.write("<section class=\"bg-light position-relative\">\r\n");
      out.write("  <!-- Svg decoration -->\r\n");
      out.write("  <figure class=\"position-absolute bottom-0 start-0 d-none d-lg-block\">\r\n");
      out.write("    <svg width=\"822.2px\" height=\"301.9px\" viewBox=\"0 0 822.2 301.9\">\r\n");
      out.write("      <path class=\"fill-warning opacity-5\" d=\"M752.5,51.9c-4.5,3.9-8.9,7.8-13.4,11.8c-51.5,45.3-104.8,92.2-171.7,101.4c-39.9,5.5-80.2-3.4-119.2-12.1 c-32.3-7.2-65.6-14.6-98.9-13.9c-66.5,1.3-128.9,35.2-175.7,64.6c-11.9,7.5-23.9,15.3-35.5,22.8c-40.5,26.4-82.5,53.8-128.4,70.7 c-2.1,0.8-4.2,1.5-6.2,2.2L0,301.9c3.3-1.1,6.7-2.3,10.2-3.5c46.1-17,88.1-44.4,128.7-70.9c11.6-7.6,23.6-15.4,35.4-22.8 c46.7-29.3,108.9-63.1,175.1-64.4c33.1-0.6,66.4,6.8,98.6,13.9c39.1,8.7,79.6,17.7,119.7,12.1C634.8,157,688.3,110,740,64.6 c4.5-3.9,9-7.9,13.4-11.8C773.8,35,797,16.4,822.2,1l-0.7-1C796.2,15.4,773,34,752.5,51.9z\"></path>\r\n");
      out.write("    </svg>\r\n");
      out.write("  </figure>\r\n");
      out.write("  <div class=\"container position-relative\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-12\">\r\n");
      out.write("        <div class=\"row align-items-center col-6\" style=\"float: left;\">\r\n");
      out.write("          <!-- Image -->\r\n");
      out.write("          <!-- <div class=\"col-6 col-md-3 text-center order-1\">\r\n");
      out.write("            <img src=\"assets/images/element/category-1.svg\" alt=\"\">\r\n");
      out.write("          </div> -->\r\n");
      out.write("          <!-- Content -->\r\n");
      out.write("          <!-- <div class=\"col-md-6 px-md-5 text-center position-relative order-md-2 mb-5 mb-md-0\">\r\n");
      out.write(" -->\r\n");
      out.write("            <!-- Svg decoration -->\r\n");
      out.write("            <figure class=\"position-absolute top-0 start-0\">\r\n");
      out.write("              <svg width=\"22px\" height=\"22px\" viewBox=\"0 0 22 22\">\r\n");
      out.write("                <polygon class=\"fill-orange\" points=\"22,8.3 13.7,8.3 13.7,0 8.3,0 8.3,8.3 0,8.3 0,13.7 8.3,13.7 8.3,22 13.7,22 13.7,13.7 22,13.7 \"></polygon>\r\n");
      out.write("              </svg>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <!-- Svg decoration -->\r\n");
      out.write("            <figure class=\"position-absolute top-0 start-50 translate-middle mt-n6 d-none d-md-block\">\r\n");
      out.write("              <svg width=\"27px\" height=\"27px\">\r\n");
      out.write("                <path class=\"fill-purple\" d=\"M13.122,5.946 L17.679,-0.001 L17.404,7.528 L24.661,5.946 L19.683,11.533 L26.244,15.056 L18.891,16.089 L21.686,23.068 L15.400,19.062 L13.122,26.232 L10.843,19.062 L4.557,23.068 L7.352,16.089 L-0.000,15.056 L6.561,11.533 L1.582,5.946 L8.839,7.528 L8.565,-0.001 L13.122,5.946 Z\"></path>\r\n");
      out.write("              </svg>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <!-- Title -->\r\n");
      out.write("            <h1 class=\"mb-3\">What do you want to share?</h1>\r\n");
      out.write("            <p class=\"mb-3\">Talk about what you like with kindred spirits online</p>\r\n");
      out.write("            <!-- Search -->\r\n");
      out.write("<!--             <form class=\"bg-body rounded p-2\">\r\n");
      out.write("              <div class=\"input-group\">\r\n");
      out.write("                <input class=\"form-control border-0 me-1\" type=\"search\" placeholder=\"Search course \">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-dark mb-0 rounded\">Search</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form> -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Image -->\r\n");
      out.write("<!--           <div class=\"col-6 col-md-3 text-center order-3\"> -->\r\n");
      out.write("          <div class=\"col-6 col-md-4 text-center order-3\" style=\"float: right;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/assets/images/element/04.svg\" alt=\"a woman listening with a headphone with a notebook on her laptop and a man holding a book spread and talking\">\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div> <!-- Row END -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div> <!-- Row END -->\r\n");
      out.write("</section>\r\n");
      out.write("<!-- =======================\r\n");
      out.write("Page Banner END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"py-4\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div id=\"listJspContainer\" class=\"row\">\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"listContainer\" class=\"col-sm-12 text-left\">\r\n");
      out.write("<!-- <div id=\"listContainer\"> -->\r\n");
      out.write("\r\n");
      out.write("\t\t<table id=\"mainList\" class=\"table table-hover\">\r\n");
      out.write("\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>No.</th>\r\n");
      out.write("<!-- \t\t\t\t\t<th>Cate.</th> --> \r\n");
      out.write("\t\t\t\t\t<th id=\"cateTh\" width=\"110px\" style=\"color:black;\">\r\n");
      out.write("\t\t\t\t\t<!-- 카테고리별 정렬 -->\r\n");
      out.write("\t\t\t\t\t<form action=\"./catelist.do\" method=\"post\" enctype=\"multipart/form-data\" name=\"postCate\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height:28px; padding:0px; margin:0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"postCate\" id=\"postCate\" class=\"form-select form-select\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"margin: top; transform: translateY(-13%); color:black;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonchange=\"this.form.submit()\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\theight: 32px;  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected value=\"\">Cate.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">일반</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">질문</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">홍보</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\">공지사항</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 40%\">Title</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 15%\">Name</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"width: 20%\">Date</th>\r\n");
      out.write("\t\t\t\t\t<th>View</th>\r\n");
      out.write("<!-- \t\t\t\t\t<th>Attach.</th> -->\r\n");
      out.write("\t\t\t\t\t<th><i class=\"bi bi-download\"></i></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");

					if(postList.size() == 0 ) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"6\">게시물 정보가 존재하지 않습니다.</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					}else{
// 							pv3: view 출력 관련
							for(PostVO pv3 : bNotiList) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr id=\"notice\">\r\n");
      out.write("\t\t\t\t\t\t<td id=\"postNo\">");
      out.print(pv3.getPostNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

				String j = null;
				int num = pv3.getPostCate();
					switch(num) {
					case 0: j ="공지사항"; break;
					case 1: j ="일반"; break;
					case 2: j ="질문"; break;
					case 3: j ="홍보"; break;
					case 8: j ="튜터신청"; break;
					case 9: j ="제재"; break;
					default: break;
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td id=\"postCate\">");
      out.print( j);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"postTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"listTitle\" style=\"text-decoration:none\" href=\"./detail.do?postNo=");
      out.print(pv3.getPostNo() );
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\tdata-bs-toggle=\"tooltip\" >");
      out.print(pv3.getPostTitle() );
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"postWriter\">");
      out.print(pv3.getPostWriter() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"postDate\">");
      out.print(pv3.getPostDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"listViewCnt\">");
      out.print(pv3.getViewCnt() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"postAtch\">\r\n");
      out.write("<!-- \t\t\t\t\t\t(view의 첨부파일 표시 자리) -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

			}
							for(PostVO pv : postList) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t \t\t\t<td id=\"postNo\">");
      out.print(pv.getPostNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t");

				String j = null;
				int num = pv.getPostCate();
					switch(num) {
					case 0: j ="공지사항"; break;
					case 1: j ="일반"; break;
					case 2: j ="질문"; break;
					case 3: j ="홍보"; break;
					case 8: j ="튜터신청"; break;
					case 9: j ="제재"; break;
					default: break;
					}
				
      out.write("\r\n");
      out.write(" \t\t \t\t\t<td id=\"postCate\">");
      out.print( j);
      out.write("</td>\r\n");
      out.write("\t\t \t\t\t<td id=\"postTitle\">\r\n");
      out.write("\t\t \t\t\t\t<a class=\"listTitle\" style=\"text-decoration:none\" href=\"./detail.do?postNo=");
      out.print(pv.getPostNo() );
      out.write("\" \r\n");
      out.write("\t\t \t\t\t\t\tdata-bs-toggle=\"tooltip\" >");
      out.print(pv.getPostTitle() );
      out.write("</a> <font style=\"font-size:80%\">[");
      out.print(pv.getCommCnt() );
      out.write("]</font>\r\n");
      out.write("\r\n");
      out.write("\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"postWriter\">");
      out.print(pv.getPostWriter() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"postDate\">");
      out.print(pv.getPostDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"listViewCnt\">");
      out.print(pv.getViewCnt() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"postAtch\">\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\t<i class=\"bi bi-box-arrow-in-down\"></i> -->\r\n");
      out.write("\t\t\t\t\t");

					long tch = pv.getAtchFileId();
					if (tch <= 0) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					}else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<i class=\"bi bi-download\"></i>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<!-- 잘못한게 없는거같은데 에러가 난다면? -> 탭 껐다 켜기 -->\r\n");
      out.write("\t\t\t\t\t<!-- JSP 수정했을 땐 서버 껐다 켤 필요 X -->\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t");

		}
	}
	
      out.write("\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 페이징 처리된 페이지 목록 시작 -->\r\n");
      out.write("<div id=\"pagination\" class=\"container mt-3\">\r\n");
      out.write("    ");

    Integer currentPageObj = (Integer) request.getAttribute("currentPage");
    Integer totalPagesObj = (Integer) request.getAttribute("totalPages");

    int currentPage = (currentPageObj != null) ? currentPageObj : 1;
    int totalPages = (totalPagesObj != null) ? totalPagesObj : 1;

    int maxPagesToShow = 5; // 보여줄 최대 페이지 수

    int startPage = Math.max(1, currentPage - maxPagesToShow / 2);
    int endPage = Math.min(startPage + maxPagesToShow - 1, totalPages);
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 목록 버튼\t -->\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-dark-soft\" style=\"float:left;\" onclick=\"location.href='./list.do'\">글목록</button>\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-dark-soft\" id=\"writeButton\" style=\"float:right;\" onclick=\"location.href='./insert.do'\">글쓰기</button>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- '이전' 버튼 -->\r\n");
      out.write("    <div class=\"container text-center col-sm-12\">\r\n");
      out.write("    \t<ul class=\"pagination justify-content-center\">\r\n");
      out.write("<!--     \t<ul class=\"pagination pagination-primary-soft rounded justify-content-center\"> -->\r\n");
      out.write("<!--     \t<ul class=\"pagination pagination-outline rounded justify-content-center\"> -->\r\n");
      out.write("\t");

		if(currentPage > 1) {
	
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"./list.do?page=");
      out.print( currentPage - 1 );
      out.write("\" class=\"page-link\"><i class=\"fas fa-angle-double-left\"></i></a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t");

		}else{
	
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('	');

		}
	
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- 페이지 목록 -->\r\n");
      out.write("\t");

	if (startPage > 1) {
	
      out.write("\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t<a href=\"./list.do?page=1\" \r\n");
      out.write("\t\t\tclass=\"page-link\">1</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t");

	}
	if (startPage > 2) {
	
      out.write("\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t<span class=\"page-item disabled\" id=\"ellipsis\"><a class=\"page-link\" href=\"#\">...</a></span>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t");

	}

	for (int i = startPage; i <= endPage; i++) {
		if (i == currentPage) {
	
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item active\">\r\n");
      out.write("\t\t\t<a class=\"page-link\" href=\"#\">\r\n");
      out.write("\t\t\t<span class=\"current-page\">\r\n");
      out.write("\t\t\t");
      out.print( i );
      out.write("\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t");

		} else {
	
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a href=\"./list.do?page=");
      out.print( i );
      out.write("\" class=\"page-link\">");
      out.print( i );
      out.write("</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t");

		}
	}

	if (endPage < totalPages - 1) {
	
      out.write("\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<span class=\"page-item disabled\" id=\"ellipsis\"><a class=\"page-link\" href=\"#\">...</a></span>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t");

	}
	if (endPage < totalPages) {
	
      out.write("\r\n");
      out.write("\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t<a href=\"./list.do?page=");
      out.print( totalPages );
      out.write("\" class=\"page-link\"> ");
      out.print( totalPages );
      out.write("</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t<!-- 페이지 목록 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("    <!-- '다음' 버튼 -->\r\n");
      out.write("\t\t");

		if(currentPage < totalPages) {
		
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"./list.do?page=");
      out.print( currentPage + 1 );
      out.write("\" class=\"page-link\"><i class=\"fas fa-angle-double-right\"></i></a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t");

		}else{
		
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t");

		}
		
      out.write("    \t \r\n");
      out.write("\t<!-- '다음' 버튼 끝 -->\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 페이징 처리된 페이지 목록 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 검색하기  -->\r\n");
      out.write("\t<div class=\"text-center\" id=\"searchContainer\">\r\n");
      out.write("\t\t\t<form method=\"get\" name=\"search\" action=\"./search.do\" id=\"searchForm\">\r\n");
      out.write("\t\t\t\t\t<div id=\"searchOptions\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" name=\"searchField\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"postTitle\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"postContent\">제목+내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"postWriter\">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"searchBox\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"검색어 입력\" \r\n");
      out.write("\t\t\t\t\t\t\tname=\"searchText\" maxlength=\"100\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"searchButton\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-outline-success\">검색</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- 검색하기 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

	if(msg.equals("성공")) {

      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("\talert('정상적으로 처리되었습니다.');\r\n");
      out.write("</script>\r\n");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("/*    $(document).ready(function(){\r\n");
      out.write("\t  //실행내용\r\n");
      out.write("\t  \r\n");
      out.write("\t}) */\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"pt-5 bg-light\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- Row START -->\r\n");
      out.write("\t\t<div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 1 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<!-- logo -->\r\n");
      out.write("\t\t\t\t<a class=\"me-0\" href=\"/nawa/index.jsp\">\r\n");
      out.write("\t\t\t\t\t<img class=\"light-mode-item h-40px\" src=\"/nawa/assets/images/title_logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"list-inline mb-0 mt-3\">\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-facebook\" href=\"#\"><i class=\"fab fa-fw fa-facebook-f\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-instagram\" href=\"#\"><i class=\"fab fa-fw fa-instagram\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-twitter\" href=\"#\"><i class=\"fab fa-fw fa-twitter\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-linkedin\" href=\"#\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a> </li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Widget 1 END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 2 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t<div class=\"row g-4\">\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Company</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">News and Blogs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Library</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Career</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Community</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Documentation</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Faq</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Forum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Sitemap</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Teaching</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Become a teacher</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">How to guide</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Widget 2 END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 3 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Contact</h5>\r\n");
      out.write("\t\t\t\t<!-- Time -->\r\n");
      out.write("\t\t\t\t<p class=\"mb-2\">\r\n");
      out.write("\t\t\t\t\tToll free:<span class=\"h6 fw-light ms-2\">+1234 568 963</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"d-block small\">(9:AM to 8:PM IST)</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"mb-0\">Email:<span class=\"h6 fw-light ms-2\">example@gmail.com</span></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row g-2 mt-2\">\r\n");
      out.write("\t\t\t\t\t<!-- Google play store button -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3 col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/nawa/assets/images/client/google-play.svg\" alt=\"\"> </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- App store button -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3 col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/nawa/assets/images/client/app-store.svg\" alt=\"app-store\"> </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> <!-- Row END -->\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<!-- Widget 3 END -->\r\n");
      out.write("\t\t</div><!-- Row END -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Divider -->\r\n");
      out.write("\t\t<hr class=\"mt-4 mb-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bottom footer -->\r\n");
      out.write("\t\t<div class=\"py-3\">\r\n");
      out.write("\t\t\t<div class=\"container px-0\">\r\n");
      out.write("\t\t\t\t<div class=\"d-lg-flex justify-content-between align-items-center py-3 text-center text-md-left\">\r\n");
      out.write("\t\t\t\t\t<!-- copyright text -->\r\n");
      out.write("\t\t\t\t\t<div class=\"text-body text-primary-hover\"> Copyrights ÃÂ©2023 Eduport. Build by <a href=\"https://www.webestica.com/\" target=\"_blank\" class=\"text-body\">Webestica</a></div>\r\n");
      out.write("\t\t\t\t\t<!-- copyright links-->\r\n");
      out.write("\t\t\t\t\t<div class=\"justify-content-center mt-3 mt-lg-0\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav list-inline justify-content-center mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Language selector -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropup mt-0 text-center text-sm-end\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"dropdown-toggle nav-link\" href=\"#\" role=\"button\" id=\"languageSwitcher\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-globe me-2\"></i>Language\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu min-w-auto\" aria-labelledby=\"languageSwitcher\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/uk.svg\" alt=\"\">English</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/gr.svg\" alt=\"\">German </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/sp.svg\" alt=\"\">French</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a class=\"nav-link\" href=\"#\">Terms of use</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a class=\"nav-link pe-0\" href=\"#\">Privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- =======================\r\n");
      out.write("Footer END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
