/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2024-01-19 01:17:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.vo.MemberVO;
import atch.vo.BoardAtchFileVO;
import java.util.List;
import board.vo.PostVO;

public final class updateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1705363831432L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1705625487156L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.vo.MemberVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("board.vo.PostVO");
    _jspx_imports_classes.add("atch.vo.BoardAtchFileVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO mv = (MemberVO) session.getAttribute("LOGIN_USER");
	if(mv == null) { 
      out.write("\r\n");
      out.write("\t\t<script>alert(\"로그인이 필요합니다\"); location.href=\"/nawa/member/signin.jsp\"</script>\r\n");
      out.write("\t");
} 

      out.write('\r');
      out.write('\n');

	PostVO pv = (PostVO) request.getAttribute("pv");
	List<BoardAtchFileVO> atchFileList = 
		(List<BoardAtchFileVO>) request.getAttribute("atchFileList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>nawa!</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Meta Tags -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<meta name=\"author\" content=\"Webestica.com\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Eduport- LMS, Education and Course Theme\">\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Favicon -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/nawa/assets/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Google Font -->\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Plugins CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/font-awesome/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/bootstrap-icons/bootstrap-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/choices/css/choices.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Theme CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Header START -->\r\n");
      out.write("<header class=\"navbar-light navbar-sticky\">\r\n");
      out.write("\t<!-- Logo Nav START -->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-xl\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Logo START -->\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">\r\n");
      out.write("\t\t\t\t<img class=\"light-mode-item navbar-brand-item\" src=\"/nawa/assets/images/5조_제목_로고-removebg-preview.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t<img class=\"dark-mode-item navbar-brand-item\" src=\"/nawa/assets/images/logo-light.svg\" alt=\"logo\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<!-- Logo END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Responsive navbar toggler -->\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler ms-auto\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\" aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-animation\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main navbar START -->\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse w-100 collapse\" id=\"navbarCollapse\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Nav Main menu START -->\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav navbar-nav-scroll mx-auto\">\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 1 Demos -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"demoMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"demoMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">게시판!</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-2.html\">Home Education</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-3.html\">Home Academy</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-4.html\">Home Course</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-5.html\">Home University</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-6.html\">Home Kindergarten</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-7.html\">Home Landing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-8.html\">Home Tutor</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-9.html\">Home School</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-10.html\">Home Abroad</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-11.html\">Home Workshop</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 2 Pages -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"pagesMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">소모임</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"pagesMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Course</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-categories.html\">Course Categories</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-grid.html\">Course Grid Classic</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-grid-2.html\">Course Grid Minimal</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-list.html\">Course List Classic</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-list-2.html\">Course List Minimal</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-detail.html\">Course Detail Classic</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-detail-min.html\">Course Detail Minimal</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-detail-adv.html\">Course Detail Advance</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-detail-module.html\">Course Detail Module</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-video-player.html\">Course Full Screen Video</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">About</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"about.html\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"contact-us.html\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"blog-grid.html\">Blog Grid</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"blog-masonry.html\">Blog Masonry</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"blog-detail.html\">Blog Detail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"pricing.html\">Pricing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Hero Banner</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"docs/snippet-hero-12.html\">Hero Form</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"docs/snippet-hero-13.html\">Hero Vector</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <p class=\"dropdown-item mb-0\">Coming soon....</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-list.html\">Instructor List</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-single.html\">Instructor Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"become-instructor.html\">Become an Instructor</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"abroad-single.html\">Abroad Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"workshop-detail.html\">Workshop Detail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"event-detail.html\">Event Detail</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Shop</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"shop.html\">Shop grid</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"shop-product-detail.html\">Product detail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"cart.html\">Cart</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"empty-cart.html\">Empty Cart</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"wishlist.html\">Wishlist</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Help</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"help-center.html\">Help Center</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"help-center-detail.html\">Help Center Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"faq.html\">FAQs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Authentication</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"sign-in.html\">Sign In</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"sign-up.html\">Sign Up</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"forgot-password.html\">Forgot Password</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Form</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"request-demo.html\">Request a demo</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"book-class.html\">Book a Class</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"request-access.html\">Free Access</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"university-admission-form.html\">Admission Form</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Specialty</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"error-404.html\">Error 404</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"coming-soon.html\">Coming Soon</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 3 Account -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"accounntMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">레슨</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"accounntMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-tie fa-fw me-1\"></i>Instructor</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-dashboard.html\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>Dashboard</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-manage-course.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>Courses</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-create-course.html\"><i class=\"bi bi-file-earmark-plus-fill fa-fw me-1\"></i>Create Course</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-added.html\"><i class=\"bi bi-file-check-fill fa-fw me-1\"></i>Course Added</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>Quiz</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-earning.html\"><i class=\"fas fa-chart-line fa-fw me-1\"></i>Earnings</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-studentlist.html\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>Students</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-order.html\"><i class=\"bi bi-cart-check-fill fa-fw me-1\"></i>Orders</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-review.html\"><i class=\"bi bi-star-fill fa-fw me-1\"></i>Reviews</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-payout.html\"><i class=\"fas fa-wallet fa-fw me-1\"></i>Payout</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>Student</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/list.do\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>강의전체보기</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-subscription.html\"><i class=\"bi bi-card-checklist fa-fw me-1\"></i>운동강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-list.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>음악강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-resume.html\"><i class=\"far fa-fw fa-file-alt me-1\"></i>어학강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>개발강의 </a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-payment-info.html\"><i class=\"bi bi-credit-card-2-front-fill fa-fw me-1\"></i>게임강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>공예강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>기타강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"admin-dashboard.html\"><i class=\"fas fa-user-cog fa-fw me-1\"></i>Admin</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-edit-profile.html\"><i class=\"fas fa-fw fa-edit me-1\"></i>Edit Profile</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-setting.html\"><i class=\"fas fa-fw fa-cog me-1\"></i>Settings</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-delete-account.html\"><i class=\"fas fa-fw fa-trash-alt me-1\"></i>Delete Profile</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown Level -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Dropdown levels</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- dropdown submenu open right -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Dropdown (end)</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"#\">Dropdown item</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"#\">Dropdown item</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"#\">Dropdown item</a> </li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- dropdown submenu open left -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropstart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\">Dropdown (start)</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"#\">Dropdown item</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"#\">Dropdown item</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"#\">Dropdown item</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- Nav Main menu END -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Nav Search START -->\r\n");
      out.write("\t\t\t\t<!-- <div class=\"nav my-3 my-xl-0 px-4 flex-nowrap align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"nav-item w-100\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"position-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control pe-5 bg-transparent\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"bg-transparent p-2 position-absolute top-50 end-0 translate-middle-y border-0 text-primary-hover text-reset\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-search fs-6 \"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- Nav Search END -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Main navbar END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ############################################ 회원일 경우 달라질헤더 부분  ############################## -->\r\n");
      out.write("\t\t\t<!-- Profile START -->\r\n");
      out.write("\t\t\t<div class=\"dropdown ms-1 ms-lg-0\">\r\n");
      out.write("\t\t\t\t<a class=\"avatar avatar-sm p-0\" href=\"#\" id=\"profileDropdown\" role=\"button\" data-bs-auto-close=\"outside\" data-bs-display=\"static\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t<img class=\"avatar-img rounded-circle\" src=\"/nawa/assets/images/avatar/anno.png\" alt=\"avatar\" onclick=\"javascript:location.href='signin.do'\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu dropdown-animation dropdown-menu-end shadow pt-3\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("\t\t\t\t\t<!-- Profile info -->\r\n");
      out.write("\t\t\t\t\t<li class=\"px-3 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Avatar -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"avatar me-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"avatar-img rounded-circle shadow\" src=\"/nawa/assets/images/avatar/01.jpg\" alt=\"avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"h6\" href=\"#\">Lori Ferguson</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"small m-0\">example@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- Links -->\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><i class=\"bi bi-person fa-fw me-2\"></i>Edit Profile</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><i class=\"bi bi-gear fa-fw me-2\"></i>Account Settings</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><i class=\"bi bi-info-circle fa-fw me-2\"></i>Help</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item bg-danger-soft-hover\" href=\"#\"><i class=\"bi bi-power fa-fw me-2\"></i>Sign Out</a></li>\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t<!-- Dark mode options START -->\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bg-light dark-mode-switch theme-icon-active d-flex align-items-center p-1 rounded mt-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm mb-0\" data-bs-theme-value=\"light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-sun fa-fw mode-switch\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<path d=\"M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<use href=\"#\"></use>\r\n");
      out.write("\t\t\t\t\t\t\t\t</svg> Light\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm mb-0\" data-bs-theme-value=\"dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-moon-stars fa-fw mode-switch\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<path d=\"M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278zM4.858 1.311A7.269 7.269 0 0 0 1.025 7.71c0 4.02 3.279 7.276 7.319 7.276a7.316 7.316 0 0 0 5.205-2.162c-.337.042-.68.063-1.029.063-4.61 0-8.343-3.714-8.343-8.29 0-1.167.242-2.278.681-3.286z\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<path d=\"M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<use href=\"#\"></use>\r\n");
      out.write("\t\t\t\t\t\t\t\t</svg> Dark\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-sm mb-0 active\" data-bs-theme-value=\"auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-circle-half fa-fw mode-switch\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<path d=\"M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<use href=\"#\"></use>\r\n");
      out.write("\t\t\t\t\t\t\t\t</svg> Auto\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t\t<!-- Dark mode options END-->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Profile START -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- Logo Nav END -->\r\n");
      out.write("</header>\r\n");
      out.write("<!-- Header END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#buttonContainer {\r\n");
      out.write("padding: 10px;\r\n");
      out.write("}\r\n");
      out.write(".updateButton{\r\n");
      out.write("border: 2px dashed teal;\r\n");
      out.write("border-radius: 10px;\r\n");
      out.write("background-color: white;\r\n");
      out.write("padding: 0px 13px;\r\n");
      out.write("font-family: 'Dongle', sans-serif;\r\n");
      out.write("font-size: 150%;\r\n");
      out.write("}\r\n");
      out.write("#updateContainer {\r\n");
      out.write("padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- </head> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <body> -->\r\n");
      out.write("<section class=\"py-4\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-sm-8 text-left\">\r\n");
      out.write("\r\n");
      out.write("  \t<form id=\"updateForm\" action=\"./update.do\" method=\"post\" enctype=\"multipart/form-data\"\r\n");
      out.write("  \t\tonsubmit=\"convertTextarea()\">\r\n");
      out.write("  \t\t<input type=\"hidden\" name=\"postNo\" value=\"");
      out.print(pv.getPostNo());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<div id=\"updateContainer\" class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"postNo\">글번호: </label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"postNo\" id=\"postNo\" class=\"form-control\" value=\"");
      out.print(pv.getPostNo());
      out.write("\" disabled>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label for=\"postWriter\">작성자: </label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"postWriter\" id=\"postWriter\" class=\"form-control\" value=\"");
      out.print(pv.getPostWriter());
      out.write("\" disabled>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label for=\"postDate\">작성일: </label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"postDate\" id=\"postDate\" class=\"form-control\" value=\"");
      out.print(pv.getPostDate());
      out.write("\" disabled>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"postCate\">분류: </label>\r\n");
      out.write("\t\t\t\t\t<select name=\"postCate\" id=\"postCate\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">일반</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">질문</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">홍보</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"8\">튜터신청</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">제재</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">공지사항</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label for=\"postTitle\">제  목: </label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"postTitle\" id=\"postTitle\" class=\"form-control\"value=\"");
      out.print(pv.getPostTitle());
      out.write("\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label for=\"postContent\">내용: </label>\r\n");
      out.write("\t\t\t\t<textarea name=\"postContent\" id=\"postContent\" class=\"form-control\" >");
      out.print(pv.getPostContent());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label for=\"atchOld\">기존 첨부파일:</label>\r\n");
      out.write("\t\t\t\t<div id=\"atchOld\">\r\n");
      out.write("\t\t\t\t");

					if(atchFileList != null) { 
							for(BoardAtchFileVO fileVO : atchFileList) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#\">");
      out.print(fileVO.getBoardOriName() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/fileDownload.do?fileId=");
      out.print(fileVO.getBoardFIndex() );
      out.write('"');
      out.write('>');
      out.print(fileVO.getBoardOriName() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t");

					}
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<label for=\"atchNew\">신규 첨부파일: </label>\r\n");
      out.write("\t\t\t\t<input type=\"file\" id=\"atchNew\" name=\"atchFile\" multiple=\"multiple\"/>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<div id=\"buttonContainer\" class=\"btn-group\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-dark-soft\" onclick=\"location.href='./list.do'\">목록</button>\r\n");
      out.write("\r\n");
      out.write("   \t\t\t<button type=\"submit\" class=\"btn btn-dark-soft\">수정</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("  \t\t</div>\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function convertTextarea() {\r\n");
      out.write("    // textarea의 내용을 가져옴\r\n");
      out.write("    let postContentValue = document.getElementById(\"postContent\").value;\r\n");
      out.write("\r\n");
      out.write("    // \\r\\n을 <br>로 치환\r\n");
      out.write("    let convertedValue = postContentValue.replace(/(\\n|\\r\\n)/g, \"<br>\");\r\n");
      out.write("\r\n");
      out.write("    // 변환된 값을 다시 textarea에 설정\r\n");
      out.write("    document.getElementById(\"postContent\").value = convertedValue;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- =======================\r\n");
      out.write("Footer START -->\r\n");
      out.write("<footer class=\"pt-5 bg-light\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- Row START -->\r\n");
      out.write("\t\t<div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 1 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<!-- logo -->\r\n");
      out.write("\t\t\t\t<a class=\"me-0\" href=\"index.html\">\r\n");
      out.write("\t\t\t\t\t<img class=\"light-mode-item h-40px\" src=\"/nawa/assets/images/5조_제목_로고-removebg-preview.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t<img class=\"dark-mode-item h-40px\" src=\"/nawa/assets/images/logo-light.svg\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<p class=\"my-3\">Eduport education theme, built specifically for the education centers which is dedicated to teaching and involve learners. </p>\r\n");
      out.write("\t\t\t\t<!-- Social media icon -->\r\n");
      out.write("\t\t\t\t<ul class=\"list-inline mb-0 mt-3\">\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-facebook\" href=\"#\"><i class=\"fab fa-fw fa-facebook-f\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-instagram\" href=\"#\"><i class=\"fab fa-fw fa-instagram\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-twitter\" href=\"#\"><i class=\"fab fa-fw fa-twitter\"></i></a> </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-inline-item\"> <a class=\"btn btn-white btn-sm shadow px-2 text-linkedin\" href=\"#\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a> </li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Widget 1 END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 2 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t<div class=\"row g-4\">\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Company</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Contact us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">News and Blogs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Library</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Career</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Community</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Documentation</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Faq</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Forum</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Sitemap</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Link block -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Teaching</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Become a teacher</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">How to guide</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Widget 2 END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Widget 3 START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t<h5 class=\"mb-2 mb-md-4\">Contact</h5>\r\n");
      out.write("\t\t\t\t<!-- Time -->\r\n");
      out.write("\t\t\t\t<p class=\"mb-2\">\r\n");
      out.write("\t\t\t\t\tToll free:<span class=\"h6 fw-light ms-2\">+1234 568 963</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"d-block small\">(9:AM to 8:PM IST)</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"mb-0\">Email:<span class=\"h6 fw-light ms-2\">example@gmail.com</span></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row g-2 mt-2\">\r\n");
      out.write("\t\t\t\t\t<!-- Google play store button -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3 col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/nawa/assets/images/client/google-play.svg\" alt=\"\"> </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- App store button -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-sm-4 col-md-3 col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"> <img src=\"/nawa/assets/images/client/app-store.svg\" alt=\"app-store\"> </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> <!-- Row END -->\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<!-- Widget 3 END -->\r\n");
      out.write("\t\t</div><!-- Row END -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Divider -->\r\n");
      out.write("\t\t<hr class=\"mt-4 mb-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bottom footer -->\r\n");
      out.write("\t\t<div class=\"py-3\">\r\n");
      out.write("\t\t\t<div class=\"container px-0\">\r\n");
      out.write("\t\t\t\t<div class=\"d-lg-flex justify-content-between align-items-center py-3 text-center text-md-left\">\r\n");
      out.write("\t\t\t\t\t<!-- copyright text -->\r\n");
      out.write("\t\t\t\t\t<div class=\"text-body text-primary-hover\"> Copyrights ©2023 Eduport. Build by <a href=\"https://www.webestica.com/\" target=\"_blank\" class=\"text-body\">Webestica</a></div>\r\n");
      out.write("\t\t\t\t\t<!-- copyright links-->\r\n");
      out.write("\t\t\t\t\t<div class=\"justify-content-center mt-3 mt-lg-0\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav list-inline justify-content-center mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Language selector -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropup mt-0 text-center text-sm-end\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"dropdown-toggle nav-link\" href=\"#\" role=\"button\" id=\"languageSwitcher\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-globe me-2\"></i>Language\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu min-w-auto\" aria-labelledby=\"languageSwitcher\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/uk.svg\" alt=\"\">English</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/gr.svg\" alt=\"\">German </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item me-4\" href=\"#\"><img class=\"fa-fw me-2\" src=\"/nawa/assets/images/flags/sp.svg\" alt=\"\">French</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a class=\"nav-link\" href=\"#\">Terms of use</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"list-inline-item\"><a class=\"nav-link pe-0\" href=\"#\">Privacy policy</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- =======================\r\n");
      out.write("Footer END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
