/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2024-01-22 05:29:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lecture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import lecture.atch.vo.AtchFileVO;
import member.vo.MemberVO;
import lecture.vo.LectureVO;
import java.util.List;
import member.vo.MemberVO;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/include/loginheader.jsp", Long.valueOf(1705900390950L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.vo.MemberVO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("lecture.atch.vo.AtchFileVO");
    _jspx_imports_classes.add("lecture.vo.LectureVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	LectureVO lv = (LectureVO) request.getAttribute("lv");
	List<LectureVO> lecList = (List<LectureVO>) request.getAttribute("lecList");
	MemberVO mv = (MemberVO) session.getAttribute("LOGIN_USER");
	List<AtchFileVO> atchList = (List<AtchFileVO>) request.getAttribute("atchList");
// 	List<AtchFileVO> atchFileList = (List<AtchFileVO>) request.getAttribute("atchFileList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	MemberVO mmv = (MemberVO) session.getAttribute("LOGIN_USER");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\">\t\t\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>nawa!</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Meta Tags -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<meta name=\"author\" content=\"Webestica.com\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Eduport- LMS, Education and Course Theme\">\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Favicon -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/nawa/assets/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Google Font -->\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Plugins CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/font-awesome/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/bootstrap-icons/bootstrap-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/vendor/choices/css/choices.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Theme CSS -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/nawa/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header START -->\r\n");
      out.write("<header class=\"navbar-light navbar-sticky\">\r\n");
      out.write("\t<!-- Logo Nav START -->\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-xl\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!-- Logo START -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">\r\n");
      out.write("\t\t\t\t<img class=\"light-mode-item navbar-brand-item\" src=\"/nawa/assets/images/5조_제목_로고-removebg-preview.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t<img class=\"dark-mode-item navbar-brand-item\" src=\"/nawa/assets/images/logo-light.svg\" alt=\"logo\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<!-- Logo END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Responsive navbar toggler -->\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler ms-auto\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\" aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-animation\">\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main navbar START -->\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse w-100 collapse\" id=\"navbarCollapse\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Nav Main menu START -->\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav navbar-nav-scroll mx-auto\">\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 1 Demos -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"demoMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"demoMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/list.do\">전체게시판</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-3.html\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-6.html\">질문게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-5.html\">익명게시판</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"index-4.html\">홍보</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 2 Pages -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"pagesMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">소모임</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"pagesMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/meetList\">모임 검색하기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">About</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Hero Banner</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-list.html\">Instructor List</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-single.html\">Instructor Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"become-instructor.html\">Become an Instructor</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"abroad-single.html\">Abroad Single</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"workshop-detail.html\">Workshop Detail</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"event-detail.html\">Event Detail</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Nav item 3 Account -->\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"accounntMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">레슨</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"accounntMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-tie fa-fw me-1\"></i>강 사</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-dashboard.html\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>Dashboard</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-manage-course.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>Courses</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-create-course.html\"><i class=\"bi bi-file-earmark-plus-fill fa-fw me-1\"></i>Create Course</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"course-added.html\"><i class=\"bi bi-file-check-fill fa-fw me-1\"></i>Course Added</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>Quiz</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-earning.html\"><i class=\"fas fa-chart-line fa-fw me-1\"></i>Earnings</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-studentlist.html\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>Students</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-order.html\"><i class=\"bi bi-cart-check-fill fa-fw me-1\"></i>Orders</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-review.html\"><i class=\"bi bi-star-fill fa-fw me-1\"></i>Reviews</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"instructor-payout.html\"><i class=\"fas fa-wallet fa-fw me-1\"></i>Payout</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Dropdown submenu -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown-submenu dropend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item dropdown-toggle\" href=\"#\"><i class=\"fas fa-user-graduate fa-fw me-1\"></i>학 생</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-start\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/list.do\"><i class=\"bi bi-grid-fill fa-fw me-1\"></i>강의전체보기</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><i class=\"bi bi-card-checklist fa-fw me-1\"></i>운동강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-list.html\"><i class=\"bi bi-basket-fill fa-fw me-1\"></i>음악강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-course-resume.html\"><i class=\"far fa-fw fa-file-alt me-1\"></i>어학강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-quiz.html\"><i class=\"bi bi-question-diamond fa-fw me-1\"></i>개발강의 </a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-payment-info.html\"><i class=\"bi bi-credit-card-2-front-fill fa-fw me-1\"></i>게임강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>공예강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"student-bookmark.html\"><i class=\"fas bi-cart-check-fill fa-fw me-1\"></i>기타강의</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a class=\"dropdown-item\" href=\"admin-dashboard.html\"><i class=\"fas fa-user-cog fa-fw me-1\"></i>Admin</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t\tNav item 5 link\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"#\" id=\"advanceMenu\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-ellipsis-h\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end min-w-auto\" data-bs-popper=\"none\">\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://support.webestica.com/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-warning fa-fw bi bi-life-preserver me-2\"></i>Support\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"docs/index.html\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-danger fa-fw bi bi-card-text me-2\"></i>Documentation\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://eduport.webestica.com/rtl/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-info fa-fw bi bi-toggle-off me-2\"></i>RTL demo\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"https://themes.getbootstrap.com/store/webestica/\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-success fa-fw bi bi-cloud-download-fill me-2\"></i>Buy Eduport!\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"docs/alerts.html\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"text-orange fa-fw bi bi-puzzle-fill me-2\"></i>Components\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> \r\n");
      out.write("                <a class=\"dropdown-item\" href=\"docs/snippets.html\">\r\n");
      out.write("                  <i class=\"text-purple fa-fw bi bi-stickies-fill me-2\"></i>Snippets\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>      \r\n");
      out.write("\t\t\t\t<!-- Nav Main menu END -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Nav Search START -->\r\n");
      out.write("\t\t\t\t<!-- <div class=\"nav my-3 my-xl-0 px-4 flex-nowrap align-items-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"nav-item w-100\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"position-relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-control pe-5 bg-transparent\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"bg-transparent p-2 position-absolute top-50 end-0 translate-middle-y border-0 text-primary-hover text-reset\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-search fs-6 \"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- Nav Search END -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Main navbar END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- ############################################ 회원일 경우 달라질헤더 부분  ############################## -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown ms-1 ms-lg-0\">\r\n");
      out.write("\t\t\t\t<a class=\"avatar avatar-sm p-0\" href=\"#\" id=\"profileDropdown\" role=\"button\" data-bs-auto-close=\"outside\" data-bs-display=\"static\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<img class=\"avatar-img rounded-circle\" src=\"/nawa/assets/images/avatar/img.png\" alt=\"avatar\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu dropdown-animation dropdown-menu-end shadow pt-3\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("\t\t\t\t\t<!-- Profile info -->\r\n");
      out.write("\t\t\t\t\t<li class=\"px-3 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Avatar -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"avatar me-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"avatar-img rounded-circle shadow\" src=\"/nawa/image/profile/");
      out.print(mmv.getStreFileNm() );
      out.write("\" alt=\"avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"h6\" href=\"#\">");
      out.print(mmv.getMem_nick() );
      out.write("</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"small m-0\">");
      out.print(mmv.getMem_email() );
      out.write("</p> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t<!-- Links -->\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myPage.jsp\"><i class=\"bi bi-person fa-fw me-2\"></i>마이 페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/edit_profile.jsp\"><i class=\"bi bi-gear fa-fw me-2\"></i>정보 수정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item bg-danger-soft-hover\" href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.do\"><i class=\"bi bi-power fa-fw me-2\"></i>로그 아웃</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><i class=\"bi bi-info-circle fa-fw me-2\"></i>Help</a></li>\r\n");
      out.write("\t\t\t\t\t<li> <hr class=\"dropdown-divider\"></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Profile END -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- Logo Nav END -->\r\n");
      out.write("</header>\r\n");
      out.write("<!-- Header END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 여기서 부터 시작 -->\r\n");
      out.write("<section class=\"pt-5 pb-0\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row g-0 g-lg-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Left sidebar START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Instructor image START -->\r\n");
      out.write("            <div class=\"card shadow p-2 mb-4 text-center\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- 사진 출력부분  -->\r\n");
      out.write("    \t\t\t");

					if(atchList != null) { 
											for(AtchFileVO atchVO : atchList) {
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/image/lecture/");
      out.print(atchVO.getStreFileNm() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

						}
										}
					
      out.write("\r\n");
      out.write("    \r\n");
      out.write("              <!-- Card body -->\r\n");
      out.write("              <div class=\"card-body px-3\">\r\n");
      out.write("                <!-- Rating -->\r\n");
      out.write("                <ul class=\"list-inline\">\r\n");
      out.write("                  <li class=\"list-inline-item me-0 small\"><i class=\"fas fa-star text-warning\"></i></li>\r\n");
      out.write("                  <li class=\"list-inline-item me-0 small\"><i class=\"fas fa-star text-warning\"></i></li>\r\n");
      out.write("                  <li class=\"list-inline-item me-0 small\"><i class=\"fas fa-star text-warning\"></i></li>\r\n");
      out.write("                  <li class=\"list-inline-item me-0 small\"><i class=\"fas fa-star text-warning\"></i></li>\r\n");
      out.write("                  <li class=\"list-inline-item me-0 small\"><i class=\"fas fa-star-half-alt text-warning\"></i></li>\r\n");
      out.write("                  <li class=\"list-inline-item ms-2 h6 fw-light mb-0\">4.5/5.0</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- Social media button -->\r\n");
      out.write("                <ul class=\"list-inline mb-0\">\r\n");
      out.write("  <li class=\"list-inline-item\">\r\n");
      out.write("    <a class=\"btn px-2 btn-sm bg-facebook\" href=\"#\"><i class=\"fab fa-fw fa-facebook-f\"></i></a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"list-inline-item\">\r\n");
      out.write("    <a class=\"btn px-2 btn-sm bg-instagram-gradient\" href=\"https://www.instagram.com/physical_gallery_egg/?hl=ko\" target=\"_blank\">\r\n");
      out.write("      <i class=\"fab fa-fw fa-instagram\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"list-inline-item\">\r\n");
      out.write("    <a class=\"btn px-2 btn-sm bg-twitter\" href=\"#\"><i class=\"fab fa-fw fa-twitter\"></i></a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"list-inline-item\">\r\n");
      out.write("    <a class=\"btn px-2 btn-sm bg-linkedin\" href=\"#\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a>\r\n");
      out.write("  </li>\r\n");
      out.write("</ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Instructor image END -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card card-body shadow p-4 mb-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Education START -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"mb-3\">Education</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Education item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex align-items-center mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-md mb-0 bg-light rounded-3\"><i class=\"fas fa-graduation-cap\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"mb-0\">Harvard University</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0 small\">Bachelor in Computer Graphics</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Education item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex align-items-center mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-md mb-0 bg-light rounded-3\"><i class=\"fas fa-graduation-cap\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"mb-0\">University of Toronto</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0 small\">Master in Computer Graphics</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Education item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex align-items-center mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-md mb-0 bg-light rounded-3\"><i class=\"fas fa-graduation-cap\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h6 class=\"mb-0\">East Ray University</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-0 small\">Bachelor in Computer Graphics</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Education END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<hr> <!-- Divider -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Skills START -->\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"mb-3\">Skills</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Progress item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overflow-hidden mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"uppercase\">Graphic design</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-sm bg-primary bg-opacity-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-primary aos\" role=\"progressbar\" data-aos=\"slide-right\" data-aos-delay=\"200\" data-aos-duration=\"1000\" data-aos-easing=\"ease-in-out\" style=\"width: 90%;\" aria-valuenow=\"90\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"progress-percent-simple h6 mb-0\">90%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Progress item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overflow-hidden mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"uppercase\">Web design</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-sm bg-success bg-opacity-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-success aos\" role=\"progressbar\" data-aos=\"slide-right\" data-aos-delay=\"200\" data-aos-duration=\"1000\" data-aos-easing=\"ease-in-out\" style=\"width: 80%;\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"progress-percent-simple h6 mb-0\">80%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Progress item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overflow-hidden mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"uppercase\">HTML/CSS</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-sm bg-warning bg-opacity-15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-warning aos\" role=\"progressbar\" data-aos=\"slide-right\" data-aos-delay=\"200\" data-aos-duration=\"1000\" data-aos-easing=\"ease-in-out\" style=\"width: 60%;\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"progress-percent-simple h6 mb-0\">60%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Progress item -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overflow-hidden mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"uppercase\">UI/UX</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-sm bg-danger bg-opacity-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar bg-danger aos\" role=\"progressbar\" data-aos=\"slide-right\" data-aos-delay=\"200\" data-aos-duration=\"1000\" data-aos-easing=\"ease-in-out\" style=\"width: 50%;\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"progress-percent-simple h6 mb-0\">50%</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Skills END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> <!-- Row End -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Left sidebar END -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<!-- Main content START -->\r\n");
      out.write("\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t<h5 class=\"mb-0\">");
      out.print( lv.getLecGrade() );
      out.write("</h5>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h1 class=\"mb-0\">");
      out.print( lv.getLecTitle() );
      out.write("</h1>\r\n");
      out.write("\t\t\t\t<p>");
      out.print( lv.getMemName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t\t<style>\r\n");
      out.write("    \t\t\t.lecture-content {\r\n");
      out.write("      \t\t\tborder: 3px solid #001; /* 테두리 스타일 및 색상을 지정합니다. */\r\n");
      out.write("      \t\t\tpadding: 10px; /* 내부 여백을 추가하여 텍스트와 테두리 사이의 공백을 지정합니다. */\r\n");
      out.write("     \t\t\twidth: 800px; /* 원하는 너비를 지정합니다. */\r\n");
      out.write("     \t\t\theight: 400px;\r\n");
      out.write("     \t\t\tborder-radius: 10px;\r\n");
      out.write("     \t\t\tbox-shadow: 5px 5px 15px rgba(0, 0, 0, 0.5);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("  \t\t\t\t</style>\r\n");
      out.write("\t\t\t\t<div class=\"lecture-content\">\r\n");
      out.write("  \t\t\t\t\t");
      out.print( lv.getLecCont() );
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Personal info -->\r\n");
      out.write("\t\t\t\t<ul class=\"list-group list-group-borderless\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item px-0\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"h6 fw-light\"><i class=\"fas fa-fw fa-envelope text-primary me-1 me-sm-3\"></i>Email:</span>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print( lv.getMemEmail() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item px-0\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"h6 fw-light\"><i class=\"fas fa-fw fa-headphones text-primary me-1 me-sm-3\"></i>Phone number:</span>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print( lv.getMemTel() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item px-0\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"h6 fw-light\"><i class=\"fas fa-fw bi bi bi-person-plus-fill text-primary me-1 me-sm-3\" ></i>recruitment:</span>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print( lv.getLecCnt() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( lv.getLecMax() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item px-0\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"h6 fw-light\"><i class=\"fas fa-fw fa-map-marker-alt text-primary me-1 me-sm-3\" ></i>Address:</span>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print( lv.getLecLoc() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Counter START -->\r\n");
      out.write("\t\t\t\t<div class=\"row mt-4 g-3\">\r\n");
      out.write("\t\t\t\t\t<!-- Counter item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-lg text-success mb-0 bg-success bg-opacity-10 rounded-3\"><i class=\"fas fa-play\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"purecounter mb-0 fw-bold\" data-purecounter-start=\"0\" data-purecounter-end=\"10\"\tdata-purecounter-delay=\"200\">0</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"mb-0 h5\">+</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-0 h6 fw-light\">Total Courses</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Counter item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-lg text-purple bg-purple bg-opacity-10 rounded-3 mb-0\"><i class=\"fas fa-users\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"purecounter mb-0 fw-bold\" data-purecounter-start=\"0\" data-purecounter-end=\"36\"\tdata-purecounter-delay=\"200\">0</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"mb-0 h5\">K+</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-0 h6 fw-light\">Total Students</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Counter item -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"icon-lg text-orange bg-orange bg-opacity-10 rounded-3 mb-0\"><i class=\"fas fa-trophy\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"purecounter mb-0 fw-bold\" data-purecounter-start=\"0\" data-purecounter-end=\"11\" data-purecounter-delay=\"200\">0</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"mb-0 h5\">+</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-0 h6 fw-light\">Years in Experience</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Counter END -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- create button -->\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"d-sm-flex justify-content-end\">\r\n");
      out.write("\t\t\t\t\t<button type=\"editbutton\" class=\"btn btn-primary mb-0\" onclick=\"location.href='update.do?lecNo=");
      out.print(lv.getLecNo() );
      out.write("'\">수정하기</button>\r\n");
      out.write("\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t<button type=\"deletebutton\" class=\"btn btn-primary mb-0\" onclick=\"location.href='delete.do?lecNo=");
      out.print(lv.getLecNo() );
      out.write("'\"> 삭제하기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"d-sm-flex justify-content-end\">\r\n");
      out.write("\t\t\t\t\t<button type=\"editbutton\" class=\"btn btn-primary mb-0\" onclick=\"location.href='involve.do?lecNo=");
      out.print(lv.getLecNo() );
      out.write("'\">신청하기</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Course START -->\r\n");
      out.write("\t\t\t\t<div class=\"row g-4 mt-4\">\r\n");
      out.write("\t\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t\t<h2>[");
      out.print( lv.getMemName() );
      out.write("] 강사의 다른 강의 리스트</h2>\r\n");
      out.write("\r\n");
      out.write("\t");

    int cardCount = 0; // 현재 행의 카드 수를 세는 변수

    for (LectureVO lecVO : lecList) {
        // lecVO의 속성에 직접 액세스할 수 있습니다. 추가적인 루프가 필요하지 않습니다.
        // 카드 생성 로직은 필요에 따라 조정하세요.

        if (cardCount % 2 == 0) {
            // 두 개의 카드마다 새로운 행 시작

      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");

        }

      out.write("\r\n");
      out.write("                <!-- 카드 아이템 시작 -->\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"card shadow h-100\">\r\n");
      out.write("                        <!-- 이미지 -->\r\n");
      out.write("                        <div class=\"card-body pb-0\">\r\n");
      out.write("                            <!-- 뱃지와 즐겨찾기 -->\r\n");
      out.write("                            <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                                <a href=\"#\" class=\"badge bg-success bg-opacity-10 text-success\">");
      out.print( lv.getLecGrade() );
      out.write("</a>\r\n");
      out.write("                                <a href=\"#\" class=\"text-danger\"><i class=\"fas fa-heart\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 제목 -->\r\n");
      out.write("                            <h5 class=\"card-title fw-normal\"><a href=\"#\">");
      out.print( lecVO.getLecTitle() );
      out.write(" </a></h5>\r\n");
      out.write("                            <p class=\"mb-2 text-truncate-2\">");
      out.print( lecVO.getLecCont() );
      out.write("</p>\r\n");
      out.write("                            <!-- 별점 -->\r\n");
      out.write("                            <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                <li class=\"list-inline-item me-0 small\"><i class=\"fas fa-star text-warning\"></i></li>\r\n");
      out.write("                                <!-- 필요에 따라 다른 별점 추가 -->\r\n");
      out.write("                                <li class=\"list-inline-item ms-2 h6 fw-light mb-0\">4.0/5.0</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 카드 푸터 -->\r\n");
      out.write("                        <div class=\"card-footer pt-0 pb-3\">\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                <span class=\"h6 fw-light mb-0\"><i class=\"far fa-clock text-danger me-2\"></i>18h 56m</span>\r\n");
      out.write("                                <span class=\"h6 fw-light mb-0\"><i class=\"fas fa-table text-orange me-2\"></i>99 강의</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 카드 아이템 종료 -->\r\n");

        cardCount++;

        if (cardCount % 2 == 0) {
            // 두 개의 카드마다 행 종료

      out.write("\r\n");
      out.write("            </div>\r\n");

        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      </main>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("// 현재 로그인한 사용자와 강의를 만든 사용자의 아이디 설정\r\n");
      out.write("var loggedInUserId = \"");
      out.print( mv.getMem_id() );
      out.write("\";\r\n");
      out.write("var lectureCreatorId = \"");
      out.print( lv.getMemId() );
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("// 버튼 요소 가져오기\r\n");
      out.write("var editButton = document.querySelector('[type=\"editbutton\"]');\r\n");
      out.write("var deleteButton = document.querySelector('[type=\"deletebutton\"]');\r\n");
      out.write("\r\n");
      out.write("// 로그인한 사용자 아이디와 강의를 만든 사용자 아이디 비교\r\n");
      out.write("if (loggedInUserId === lectureCreatorId) {\r\n");
      out.write("    // 사용자 권한이 있는 경우: 수정, 삭제 버튼 표시\r\n");
      out.write("    editButton.style.display = \"inline-block\"; // 수정 버튼을 보이도록 설정\r\n");
      out.write("    deleteButton.style.display = \"inline-block\"; // 삭제 버튼을 보이도록 설정\r\n");
      out.write("} else {\r\n");
      out.write("    // 사용자 권한이 없는 경우: 수정, 삭제 버튼 감추기\r\n");
      out.write("    editButton.style.display = \"none\"; // 수정 버튼을 감추도록 설정\r\n");
      out.write("    deleteButton.style.display = \"none\"; // 삭제 버튼을 감추도록 설정\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
