/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2024-01-22 06:42:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Eduport - LMS, Education and Course Theme</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Meta Tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"author\" content=\"Webestica.com\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Eduport- LMS, Education and Course Theme\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../assets/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap\">\r\n");
      out.write("\r\n");
      out.write("<!-- Plugins CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../assets/vendor/font-awesome/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../assets/vendor/bootstrap-icons/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://www.google.com/recaptcha/api.js\" async defer></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- **************** MAIN CONTENT START **************** -->\r\n");
      out.write("\t<main>\r\n");
      out.write("\t\t<section\r\n");
      out.write("\t\t\tclass=\"p-0 d-flex align-items-center position-relative overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<!-- left -->\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-12 col-lg-6 d-md-flex align-items-center justify-content-center bg-primary bg-opacity-10\">\r\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\tclass=\"col-12 col-lg-6 d-md-flex align-items-center justify-content-center bg-primary bg-opacity-10 vh-lg-100\" style=\"height: 100%;\"> -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"p-3 p-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"fw-bold\">저희 사이트를 찾아주셔서 감사합니다!</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"mb-0 h6 fw-light\">나와 같이 놀자!</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Right -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-12 col-lg-6 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row my-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10 col-xl-8 m-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"assets/images/element/03.svg\" class=\"h-40px mb-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Form START -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<form id=\"frm\" action=\"");
      out.print(request.getContextPath());
      out.write("/signUp.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <form id=\"frm\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- ID 아이디-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"form-label\">ID *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-text bg-light rounded-start border-0 text-secondary px-3\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi \"></i></span> <input type=\"text\" id=\"id\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"ID\" name=\"mem_id\" required\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpattern=\"[a-zA-Z][a-zA-Z0-9]{3,7}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\" style=\"text-align: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"disp\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Password -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"inputPassword5\" class=\"form-label\">Password\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t*</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-text bg-light rounded-start border-0 text-secondary px-3\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas \"></i></span> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"*********\" name=\"mem_pass\" required\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpattern=\"(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])(?=.*?[!@#_&amp;\\+\\|]).{10,}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 생년월일 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"form-label\">생년월일 *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"bir\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"mem_bir\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"form-label\">이름 *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-text bg-light rounded-start border-0 text-secondary px-3\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi \"></i></span> <input type=\"text\" id=\"nick\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"mem_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"이름\" required pattern=\"{2,8}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"form-label\">별명 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-text bg-light rounded-start border-0 text-secondary px-3\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi \"></i></span> <input type=\"text\" id=\"nick\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tname=\"nickName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"미 입력시 john doe로 고정\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"form-label\">전화번호 *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-text bg-light rounded-start border-0 text-secondary px-3\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi \"></i></span> <input type=\"text\" id=\"phone\" name=\"phone\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"'-'를 빼고 입력하세요\" required\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpattern=\"[0][1][0-1]{1}[0-9]{3,4}[0-9]{4}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- email -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\" class=\"form-label\">Email\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t*</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-text bg-light rounded-start border-0 text-secondary px-3\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"bi \"></i></span> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Email\" id=\"exampleInputEmail1\" name=\"mem_mail\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpattern=\"[a-zA-Z0-9]+@[a-zA-Z0-9]+(\\.[a-z]+){1,2}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 주소 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style='display: none' class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"postno\" class=\"control-label col-sm-2\">우편번호<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"rq\"> *</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input div style='display: none' type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"postAddr\" name=\"mem_zip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"form-label\">주소 1 *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"addr1\" name=\"mem_add1\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"form-label\">주소 2 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control border-0 bg-light rounded-end ps-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"addr2\" name=\"mem_add2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"addrBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-info btn-sm\">주소검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Check box -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"form-check-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"checkbox-1\"> <label class=\"form-check-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfor=\"checkbox-1\">정보제공에 동의합니다</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"align-items-center mt-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"d-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-primary mb-0\"  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary mb-0\" onclick='singUp()'>Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tUp</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Social buttons -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Divider with text -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"position-relative my-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"small position-absolute top-50 start-50 translate-middle bg-body px-5\">Or</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Social btn -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xxl-6 d-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn bg-google mb-2 mb-xxl-0\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fab fa-fw fa-google text-white me-2\"></i>Signup with\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tGoogle</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Social btn -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xxl-6 d-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn bg-facebook mb-0\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fab fa-fw fa-facebook-f me-2\"></i>Signup with Facebook</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Sign up link -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mt-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Already have an account?<a href=\"sign-in.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tSign in here</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<!-- **************** MAIN CONTENT END **************** -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Back to top -->\r\n");
      out.write("\t<div class=\"back-top\">\r\n");
      out.write("\t\t<i\r\n");
      out.write("\t\t\tclass=\"bi bi-arrow-up-short position-absolute top-50 start-50 translate-middle\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"captcha.do\" method=\"post\">\r\n");
      out.write("\t\t<button class=\"g-recaptcha\"\r\n");
      out.write("\t\t\tdata-sitekey=\"6LcjWFIpAAAAAOeiSZ-EriNEV_9mbRzZ731xKP1P\"\r\n");
      out.write("\t\t\tdata-callback=\"onSubmit\" data-action=\"submit\">Submit</button>\r\n");
      out.write("\t</form> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://www.google.com/recaptcha/api.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <script>\r\n");
      out.write("\t\tfunction onSubmit(token) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"demo-form\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap JS -->\r\n");
      out.write("\t<script src=\"assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template Functions -->\r\n");
      out.write("\t<script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//id 중복체크\r\n");
      out.write("\t\t//$(\"#idChk\").on('click', function() {});\r\n");
      out.write("\t\t$('#id').on('keyup', function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t//type: '', 제이쿼리에서는 생략가능\r\n");
      out.write("\t\t\t\turl : 'idChk.jsp',\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tid : $(\"#id\").val()\r\n");
      out.write("\t\t\t\t}, //제이쿼리에서는 객체형태도 key=value형태로 자동변환되어 넘어감\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\tif (data.rst == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t$('#disp').text(data.msg).css('color', 'green');\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('#disp').text(data.msg).css('color', 'red');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr) {\r\n");
      out.write("\t\t\t\t\talert(xhr.status);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'json' //생략시 넘어오는 응답 정보 타입을 자동으로 맞춰줌\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//주소검색 api\r\n");
      out.write("\t\t$(\"#addrBtn\").on('click', function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\tvar addr = ''; // 주소 변수\r\n");
      out.write("\t\t\t\t\tvar extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t//사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("\t\t\t\t\tif (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("\t\t\t\t\t\taddr = data.roadAddress;\r\n");
      out.write("\t\t\t\t\t} else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("\t\t\t\t\t\taddr = data.jibunAddress;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t// document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"addr1\").value = addr;\r\n");
      out.write("\t\t\t\t\t// 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"addr2\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction singUp() {\r\n");
      out.write("\t\t\t//checkbox-1\r\n");
      out.write("\t\t\tconst checkbox = document.getElementById('checkbox-1');\r\n");
      out.write("\t\t\tif (!checkbox.checked) {\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\talert(\"정보제공동의바람\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
