/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2024-02-13 10:42:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.scripttest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class question02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/pageModule/headPart.jsp", Long.valueOf(1706056799332L));
    _jspx_dependants.put("/pageModule/header.jsp", Long.valueOf(1705977547921L));
    _jspx_dependants.put("/pageModule/footer.jsp", Long.valueOf(1705977677153L));
    _jspx_dependants.put("/pageModule/footerPart.jsp", Long.valueOf(1705977824107L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("    <title>쉽게 배우는 JSP 웹 프로그래밍</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/images/favicon.svg\" />\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Web Font -->\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lato&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ========================= CSS here ========================= -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/bootstrap.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/LineIcons.2.0.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/animate.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/tiny-slider.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/glightbox.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/main.css\" />\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write(" \t\tvar html = \"\";\r\n");
      out.write("\t\tvar ele1 = null;\r\n");
      out.write("\t\tvar ele2 = null;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar print = $(\"#process\");\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t$(\"td\").on(\"click\", function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ele1 == null || ele2 == null){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(ele1 == null) {\r\n");
      out.write("\t\t\t\t\tele1 = $(this);\r\n");
      out.write("\t\t\t\t\tele1.css(\"background-color\", \"yellow\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tele2 = $(this);\r\n");
      out.write("\t\t\t\t\tele2.css(\"background-color\", \"yellow\");\r\n");
      out.write("\t\t\t\t\tprint.html(ele1.text() + \"님과 \" + ele2.text() + \"님을 변경\");\r\n");
      out.write("\t\t\t\t\tvar temp = ele1.text();\r\n");
      out.write("\t\t\t\t\tele1.text(ele2.text());\r\n");
      out.write("\t\t\t\t\tele2.text(temp);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tele1.css(\"background-color\", \"transparent\");\r\n");
      out.write("\t\t\t\t\tele2.css(\"background-color\", \"transparent\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tele1 = null;\r\n");
      out.write("\t\t\t\t\tele2 = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t//animation: blink-effect 1s step-end infinite;\r\n");
      out.write(" \t\t//animation: textLoop 10s linear infinite;\r\n");
      out.write("/* \t\t$(\"#clickBtn\").on(\"click\", function(){\r\n");
      out.write("\t\t    var table = $(\"table\");\r\n");
      out.write("\t\t    //.css('animation', 'blink-effect 1s step-end infinite')\r\n");
      out.write("\t\t    table.find(\"td:contains('김현태')\").css( {\"color\": \"blue\", \"animation\": \"textLoop 10s linear infinite;\"} );\r\n");
      out.write("\t\t    var tt = \"<table class='table table-bordered' style='text-align:center; font-size:24px;'>\" + table.html() +\"</table>\";\r\n");
      out.write("\t\t    table.find(\"td:contains('김현태')\").css(\"color\", \"black\");\r\n");
      out.write("\t\t    //tt.find(\"td:contains('김현태')\").css(\"color\", \"blue\");\r\n");
      out.write("\t\t    //console.log(tt);\r\n");
      out.write("\t\t    $(\"#output\").html( tt );\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t// 출력 버튼 클릭시(현재 앉은 자리 출력 위한 이벤트)\r\n");
      out.write(" \t\t$(\"#clickBtn\").on(\"click\", function(){\r\n");
      out.write(" \t\t\t$(\"#output\").html(\"\");\r\n");
      out.write(" \t\t\tvar tds = document.getElementsByTagName(\"td\");\r\n");
      out.write(" \t\t\tvar html = \"<table class='table table-bordered' style='text-align:center; font-size:24px;'><tr>\";\r\n");
      out.write(" \t\t\tfor(var i = 1; i <= tds.length; i++){\r\n");
      out.write(" \t\t\t\tif(tds[i-1].innerText == \"김현태\"){\r\n");
      out.write(" \t\t\t\t\thtml += \"<td width='10%'><marquee><font color='blue'>\"+tds[i-1].innerText+\"</font></marquee></td>\";\t\r\n");
      out.write(" \t\t\t\t}else{\r\n");
      out.write(" \t\t\t\t\thtml += \"<td width='10%'>\" + tds[i-1].innerText + \"</td>\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t\tif(i % 9 == 0){\r\n");
      out.write(" \t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t\thtml += \"</table>\";\r\n");
      out.write(" \t\t\t$(\"#output\").html(html);\r\n");
      out.write(" \t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    <div class=\"preloader\">\r\n");
      out.write("        <div class=\"preloader-inner\">\r\n");
      out.write("            <div class=\"preloader-icon\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"breadcrumbs\" style=\"padding-top:40px;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("                    <div class=\"breadcrumbs-content\">\r\n");
      out.write("                        <h1 class=\"page-title\">JSP 개요</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 col-md-6 col-12\">\r\n");
      out.write("                    <ul class=\"breadcrumb-nav\">\r\n");
      out.write("                        <li><a href=\"/\">INDEX</a></li>\r\n");
      out.write("                        <li>CH01</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"about-us section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-12 col-md-12 col-12\">\r\n");
      out.write("                    <div class=\"content-left wow fadeInLeft\" data-wow-delay=\".3s\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<caption>앞(SEM PC 자리)</caption>\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-bordered\" style=\"text-align:center; font-size:24px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr height=\"80px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\">민경선</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\">성이수</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\">이명문</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\">조재훈</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\">최윤서</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\">안희재</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\">권예은</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"10%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr height=\"80px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>신하림</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>이영주</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>김나혜</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>김영상</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>최현명</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>최소희</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>홍진영</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>임민혁</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr height=\"80px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>김다애</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>송현지</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>김현태</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>김태원</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>이수진</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>선민수</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>서어진</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr height=\"80px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>백지은</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>최현흠</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p id=\"count\"></p>\r\n");
      out.write("\t\t\t\t\t\t<h4 id=\"process\"></h4>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<hr/><br/>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"clickBtn\">출력</button>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"output\"></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer-bottom\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                                <p class=\"copyright-text\"><a>대덕인재개발원 JSP</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- ========================= scroll-top ========================= -->\r\n");
      out.write("    <a href=\"#\" class=\"scroll-top btn-hover\">\r\n");
      out.write("        <i class=\"lni lni-chevron-up\"></i>\r\n");
      out.write("    </a>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write(" <!-- ========================= JS here ========================= -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/tiny-slider.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/glightbox.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/count-up.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        //====== Clients Logo Slider\r\n");
      out.write("        tns({\r\n");
      out.write("            container: '.client-logo-carousel',\r\n");
      out.write("            slideBy: 'page',\r\n");
      out.write("            autoplay: true,\r\n");
      out.write("            autoplayButtonOutput: false,\r\n");
      out.write("            mouseDrag: true,\r\n");
      out.write("            gutter: 15,\r\n");
      out.write("            nav: false,\r\n");
      out.write("            controls: false,\r\n");
      out.write("            responsive: {\r\n");
      out.write("                0: {\r\n");
      out.write("                    items: 1,\r\n");
      out.write("                },\r\n");
      out.write("                540: {\r\n");
      out.write("                    items: 3,\r\n");
      out.write("                },\r\n");
      out.write("                768: {\r\n");
      out.write("                    items: 4,\r\n");
      out.write("                },\r\n");
      out.write("                992: {\r\n");
      out.write("                    items: 4,\r\n");
      out.write("                },\r\n");
      out.write("                1170: {\r\n");
      out.write("                    items: 6,\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
